// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateAgentOperation               OperationName = "CreateAgent"
	CreateAgenticApplicationOperation  OperationName = "CreateAgenticApplication"
	DeleteAgentOperation               OperationName = "DeleteAgent"
	DeleteAgenticApplicationOperation  OperationName = "DeleteAgenticApplication"
	GetAgentOperation                  OperationName = "GetAgent"
	GetAgenticApplicationOperation     OperationName = "GetAgenticApplication"
	GetServiceProviderConfigOperation  OperationName = "GetServiceProviderConfig"
	ListAgenticApplicationsOperation   OperationName = "ListAgenticApplications"
	ListAgentsOperation                OperationName = "ListAgents"
	PatchAgentOperation                OperationName = "PatchAgent"
	PatchAgenticApplicationOperation   OperationName = "PatchAgenticApplication"
	ReplaceAgentOperation              OperationName = "ReplaceAgent"
	ReplaceAgenticApplicationOperation OperationName = "ReplaceAgenticApplication"
)
