// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// DeleteAgentParams is parameters of deleteAgent operation.
type DeleteAgentParams struct {
	// The unique identifier of the resource.
	ID string
}

func unpackDeleteAgentParams(packed middleware.Parameters) (params DeleteAgentParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(string)
	}
	return params
}

func decodeDeleteAgentParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteAgentParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteAgenticApplicationParams is parameters of deleteAgenticApplication operation.
type DeleteAgenticApplicationParams struct {
	// The unique identifier of the resource.
	ID string
}

func unpackDeleteAgenticApplicationParams(packed middleware.Parameters) (params DeleteAgenticApplicationParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(string)
	}
	return params
}

func decodeDeleteAgenticApplicationParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteAgenticApplicationParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetAgentParams is parameters of getAgent operation.
type GetAgentParams struct {
	// Comma-separated list of attributes to include in the response.
	Attributes OptString `json:",omitempty,omitzero"`
	// Comma-separated list of attributes to exclude from the response.
	ExcludedAttributes OptString `json:",omitempty,omitzero"`
	// The unique identifier of the resource.
	ID string
}

func unpackGetAgentParams(packed middleware.Parameters) (params GetAgentParams) {
	{
		key := middleware.ParameterKey{
			Name: "attributes",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Attributes = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "excludedAttributes",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ExcludedAttributes = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(string)
	}
	return params
}

func decodeGetAgentParams(args [1]string, argsEscaped bool, r *http.Request) (params GetAgentParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: attributes.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "attributes",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotAttributesVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotAttributesVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Attributes.SetTo(paramsDotAttributesVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "attributes",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: excludedAttributes.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "excludedAttributes",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotExcludedAttributesVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotExcludedAttributesVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ExcludedAttributes.SetTo(paramsDotExcludedAttributesVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "excludedAttributes",
			In:   "query",
			Err:  err,
		}
	}
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetAgenticApplicationParams is parameters of getAgenticApplication operation.
type GetAgenticApplicationParams struct {
	// Comma-separated list of attributes to include in the response.
	Attributes OptString `json:",omitempty,omitzero"`
	// Comma-separated list of attributes to exclude from the response.
	ExcludedAttributes OptString `json:",omitempty,omitzero"`
	// The unique identifier of the resource.
	ID string
}

func unpackGetAgenticApplicationParams(packed middleware.Parameters) (params GetAgenticApplicationParams) {
	{
		key := middleware.ParameterKey{
			Name: "attributes",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Attributes = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "excludedAttributes",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ExcludedAttributes = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(string)
	}
	return params
}

func decodeGetAgenticApplicationParams(args [1]string, argsEscaped bool, r *http.Request) (params GetAgenticApplicationParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: attributes.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "attributes",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotAttributesVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotAttributesVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Attributes.SetTo(paramsDotAttributesVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "attributes",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: excludedAttributes.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "excludedAttributes",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotExcludedAttributesVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotExcludedAttributesVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ExcludedAttributes.SetTo(paramsDotExcludedAttributesVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "excludedAttributes",
			In:   "query",
			Err:  err,
		}
	}
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListAgenticApplicationsParams is parameters of listAgenticApplications operation.
type ListAgenticApplicationsParams struct {
	// SCIM filter expression.
	Filter OptString `json:",omitempty,omitzero"`
	// 1-based index of the first result to return.
	StartIndex OptInt `json:",omitempty,omitzero"`
	// Maximum number of results to return.
	Count OptInt `json:",omitempty,omitzero"`
	// Attribute to sort by.
	SortBy OptString `json:",omitempty,omitzero"`
	// Sort order (ascending or descending).
	SortOrder OptSortOrder `json:",omitempty,omitzero"`
	// Comma-separated list of attributes to include in the response.
	Attributes OptString `json:",omitempty,omitzero"`
	// Comma-separated list of attributes to exclude from the response.
	ExcludedAttributes OptString `json:",omitempty,omitzero"`
}

func unpackListAgenticApplicationsParams(packed middleware.Parameters) (params ListAgenticApplicationsParams) {
	{
		key := middleware.ParameterKey{
			Name: "filter",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Filter = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "startIndex",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.StartIndex = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "count",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Count = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "sortBy",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.SortBy = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "sortOrder",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.SortOrder = v.(OptSortOrder)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "attributes",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Attributes = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "excludedAttributes",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ExcludedAttributes = v.(OptString)
		}
	}
	return params
}

func decodeListAgenticApplicationsParams(args [0]string, argsEscaped bool, r *http.Request) (params ListAgenticApplicationsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: filter.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "filter",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotFilterVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotFilterVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Filter.SetTo(paramsDotFilterVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "filter",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: startIndex.
	{
		val := int(1)
		params.StartIndex.SetTo(val)
	}
	// Decode query: startIndex.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "startIndex",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotStartIndexVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotStartIndexVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.StartIndex.SetTo(paramsDotStartIndexVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.StartIndex.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           1,
							MaxSet:        false,
							Max:           0,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "startIndex",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: count.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "count",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCountVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotCountVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Count.SetTo(paramsDotCountVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Count.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           0,
							MaxSet:        false,
							Max:           0,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "count",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: sortBy.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "sortBy",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotSortByVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotSortByVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.SortBy.SetTo(paramsDotSortByVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sortBy",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: sortOrder.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "sortOrder",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotSortOrderVal SortOrder
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotSortOrderVal = SortOrder(c)
					return nil
				}(); err != nil {
					return err
				}
				params.SortOrder.SetTo(paramsDotSortOrderVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.SortOrder.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sortOrder",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: attributes.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "attributes",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotAttributesVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotAttributesVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Attributes.SetTo(paramsDotAttributesVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "attributes",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: excludedAttributes.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "excludedAttributes",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotExcludedAttributesVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotExcludedAttributesVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ExcludedAttributes.SetTo(paramsDotExcludedAttributesVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "excludedAttributes",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// ListAgentsParams is parameters of listAgents operation.
type ListAgentsParams struct {
	// SCIM filter expression.
	Filter OptString `json:",omitempty,omitzero"`
	// 1-based index of the first result to return.
	StartIndex OptInt `json:",omitempty,omitzero"`
	// Maximum number of results to return.
	Count OptInt `json:",omitempty,omitzero"`
	// Attribute to sort by.
	SortBy OptString `json:",omitempty,omitzero"`
	// Sort order (ascending or descending).
	SortOrder OptSortOrder `json:",omitempty,omitzero"`
	// Comma-separated list of attributes to include in the response.
	Attributes OptString `json:",omitempty,omitzero"`
	// Comma-separated list of attributes to exclude from the response.
	ExcludedAttributes OptString `json:",omitempty,omitzero"`
}

func unpackListAgentsParams(packed middleware.Parameters) (params ListAgentsParams) {
	{
		key := middleware.ParameterKey{
			Name: "filter",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Filter = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "startIndex",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.StartIndex = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "count",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Count = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "sortBy",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.SortBy = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "sortOrder",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.SortOrder = v.(OptSortOrder)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "attributes",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Attributes = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "excludedAttributes",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ExcludedAttributes = v.(OptString)
		}
	}
	return params
}

func decodeListAgentsParams(args [0]string, argsEscaped bool, r *http.Request) (params ListAgentsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: filter.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "filter",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotFilterVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotFilterVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Filter.SetTo(paramsDotFilterVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "filter",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: startIndex.
	{
		val := int(1)
		params.StartIndex.SetTo(val)
	}
	// Decode query: startIndex.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "startIndex",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotStartIndexVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotStartIndexVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.StartIndex.SetTo(paramsDotStartIndexVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.StartIndex.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           1,
							MaxSet:        false,
							Max:           0,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "startIndex",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: count.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "count",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCountVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotCountVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Count.SetTo(paramsDotCountVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Count.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           0,
							MaxSet:        false,
							Max:           0,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "count",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: sortBy.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "sortBy",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotSortByVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotSortByVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.SortBy.SetTo(paramsDotSortByVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sortBy",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: sortOrder.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "sortOrder",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotSortOrderVal SortOrder
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotSortOrderVal = SortOrder(c)
					return nil
				}(); err != nil {
					return err
				}
				params.SortOrder.SetTo(paramsDotSortOrderVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.SortOrder.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sortOrder",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: attributes.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "attributes",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotAttributesVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotAttributesVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Attributes.SetTo(paramsDotAttributesVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "attributes",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: excludedAttributes.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "excludedAttributes",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotExcludedAttributesVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotExcludedAttributesVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ExcludedAttributes.SetTo(paramsDotExcludedAttributesVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "excludedAttributes",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// PatchAgentParams is parameters of patchAgent operation.
type PatchAgentParams struct {
	// The unique identifier of the resource.
	ID string
}

func unpackPatchAgentParams(packed middleware.Parameters) (params PatchAgentParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(string)
	}
	return params
}

func decodePatchAgentParams(args [1]string, argsEscaped bool, r *http.Request) (params PatchAgentParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// PatchAgenticApplicationParams is parameters of patchAgenticApplication operation.
type PatchAgenticApplicationParams struct {
	// The unique identifier of the resource.
	ID string
}

func unpackPatchAgenticApplicationParams(packed middleware.Parameters) (params PatchAgenticApplicationParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(string)
	}
	return params
}

func decodePatchAgenticApplicationParams(args [1]string, argsEscaped bool, r *http.Request) (params PatchAgenticApplicationParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ReplaceAgentParams is parameters of replaceAgent operation.
type ReplaceAgentParams struct {
	// The unique identifier of the resource.
	ID string
}

func unpackReplaceAgentParams(packed middleware.Parameters) (params ReplaceAgentParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(string)
	}
	return params
}

func decodeReplaceAgentParams(args [1]string, argsEscaped bool, r *http.Request) (params ReplaceAgentParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ReplaceAgenticApplicationParams is parameters of replaceAgenticApplication operation.
type ReplaceAgenticApplicationParams struct {
	// The unique identifier of the resource.
	ID string
}

func unpackReplaceAgenticApplicationParams(packed middleware.Parameters) (params ReplaceAgenticApplicationParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(string)
	}
	return params
}

func decodeReplaceAgenticApplicationParams(args [1]string, argsEscaped bool, r *http.Request) (params ReplaceAgenticApplicationParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
