// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateAgent implements createAgent operation.
//
// Create a new agent resource.
//
// POST /Agents
func (UnimplementedHandler) CreateAgent(ctx context.Context, req *AgentCreate) (r CreateAgentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAgenticApplication implements createAgenticApplication operation.
//
// Create a new agentic application resource.
//
// POST /AgenticApplications
func (UnimplementedHandler) CreateAgenticApplication(ctx context.Context, req *AgenticApplicationCreate) (r CreateAgenticApplicationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAgent implements deleteAgent operation.
//
// Delete an existing agent resource.
//
// DELETE /Agents/{id}
func (UnimplementedHandler) DeleteAgent(ctx context.Context, params DeleteAgentParams) (r DeleteAgentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAgenticApplication implements deleteAgenticApplication operation.
//
// Delete an existing agentic application resource.
//
// DELETE /AgenticApplications/{id}
func (UnimplementedHandler) DeleteAgenticApplication(ctx context.Context, params DeleteAgenticApplicationParams) (r DeleteAgenticApplicationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAgent implements getAgent operation.
//
// Retrieve a single agent by its unique identifier.
//
// GET /Agents/{id}
func (UnimplementedHandler) GetAgent(ctx context.Context, params GetAgentParams) (r GetAgentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAgenticApplication implements getAgenticApplication operation.
//
// Retrieve a single agentic application by its unique identifier.
//
// GET /AgenticApplications/{id}
func (UnimplementedHandler) GetAgenticApplication(ctx context.Context, params GetAgenticApplicationParams) (r GetAgenticApplicationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetServiceProviderConfig implements getServiceProviderConfig operation.
//
// Retrieve the service provider configuration including agent extension support.
//
// GET /ServiceProviderConfig
func (UnimplementedHandler) GetServiceProviderConfig(ctx context.Context) (r GetServiceProviderConfigRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAgenticApplications implements listAgenticApplications operation.
//
// Retrieve a list of agentic applications. Supports SCIM filtering on name, externalId, and
// applicationUrls.value.
//
// GET /AgenticApplications
func (UnimplementedHandler) ListAgenticApplications(ctx context.Context, params ListAgenticApplicationsParams) (r ListAgenticApplicationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAgents implements listAgents operation.
//
// Retrieve a list of agents. Supports SCIM filtering on name and externalId.
//
// GET /Agents
func (UnimplementedHandler) ListAgents(ctx context.Context, params ListAgentsParams) (r ListAgentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PatchAgent implements patchAgent operation.
//
// Partially update an existing agent resource using SCIM PATCH operations.
//
// PATCH /Agents/{id}
func (UnimplementedHandler) PatchAgent(ctx context.Context, req *PatchRequest, params PatchAgentParams) (r PatchAgentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PatchAgenticApplication implements patchAgenticApplication operation.
//
// Partially update an existing agentic application resource using SCIM PATCH operations.
//
// PATCH /AgenticApplications/{id}
func (UnimplementedHandler) PatchAgenticApplication(ctx context.Context, req *PatchRequest, params PatchAgenticApplicationParams) (r PatchAgenticApplicationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReplaceAgent implements replaceAgent operation.
//
// Replace an existing agent resource entirely.
//
// PUT /Agents/{id}
func (UnimplementedHandler) ReplaceAgent(ctx context.Context, req *AgentCreate, params ReplaceAgentParams) (r ReplaceAgentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReplaceAgenticApplication implements replaceAgenticApplication operation.
//
// Replace an existing agentic application resource entirely.
//
// PUT /AgenticApplications/{id}
func (UnimplementedHandler) ReplaceAgenticApplication(ctx context.Context, req *AgenticApplicationCreate, params ReplaceAgenticApplicationParams) (r ReplaceAgenticApplicationRes, _ error) {
	return r, ht.ErrNotImplemented
}
