// Code generated by ogen, DO NOT EDIT.

package api

import (
	"bytes"
	"net/http"

	"github.com/go-faster/jx"
	ht "github.com/ogen-go/ogen/http"
)

func encodeCreateAgentRequest(
	req *AgentCreate,
	r *http.Request,
) error {
	const contentType = "application/scim+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodeCreateAgenticApplicationRequest(
	req *AgenticApplicationCreate,
	r *http.Request,
) error {
	const contentType = "application/scim+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodePatchAgentRequest(
	req *PatchRequest,
	r *http.Request,
) error {
	const contentType = "application/scim+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodePatchAgenticApplicationRequest(
	req *PatchRequest,
	r *http.Request,
) error {
	const contentType = "application/scim+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodeReplaceAgentRequest(
	req *AgentCreate,
	r *http.Request,
) error {
	const contentType = "application/scim+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodeReplaceAgenticApplicationRequest(
	req *AgenticApplicationCreate,
	r *http.Request,
) error {
	const contentType = "application/scim+json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}
