// Code generated by ogen, DO NOT EDIT.
package api

type CreateAgentRes interface {
	createAgentRes()
}

type CreateAgenticApplicationRes interface {
	createAgenticApplicationRes()
}

type DeleteAgentRes interface {
	deleteAgentRes()
}

type DeleteAgenticApplicationRes interface {
	deleteAgenticApplicationRes()
}

type GetAgentRes interface {
	getAgentRes()
}

type GetAgenticApplicationRes interface {
	getAgenticApplicationRes()
}

type GetServiceProviderConfigRes interface {
	getServiceProviderConfigRes()
}

type ListAgenticApplicationsRes interface {
	listAgenticApplicationsRes()
}

type ListAgentsRes interface {
	listAgentsRes()
}

type PatchAgentRes interface {
	patchAgentRes()
}

type PatchAgenticApplicationRes interface {
	patchAgenticApplicationRes()
}

type ReplaceAgentRes interface {
	replaceAgentRes()
}

type ReplaceAgenticApplicationRes interface {
	replaceAgenticApplicationRes()
}
