// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/url"
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

// An AI agent with its own identifier, metadata, and privileges.
// Schema URI: urn:ietf:params:scim:schemas:core:2.0:Agent.
// Ref: #/components/schemas/Agent
type Agent struct {
	// The schemas used for this resource.
	Schemas []string `json:"schemas"`
	// The unique identifier for the agent.
	ID OptString `json:"id"`
	// An external identifier for the agent.
	ExternalId OptString `json:"externalId"`
	Meta       OptMeta   `json:"meta"`
	// The unique name of the agent. REQUIRED.
	Name string `json:"name"`
	// A human-readable display name for the agent.
	DisplayName OptString `json:"displayName"`
	// A description of the agent.
	Description OptString `json:"description"`
	// The type of agent (e.g., Assistant, Researcher, Chat bot).
	AgentType OptString `json:"agentType"`
	// Whether the agent is administratively active.
	Active OptBool `json:"active"`
	// The subject for inbound token federation correlation.
	Subject OptString `json:"subject"`
	// Groups to which the agent belongs.
	Groups []GroupReference `json:"groups"`
	// Entitlements granted to the agent.
	Entitlements []Entitlement `json:"entitlements"`
	// Roles assigned to the agent.
	Roles []Role `json:"roles"`
	// X.509 certificates associated with the agent.
	X509Certificates []X509Certificate `json:"x509Certificates"`
	// Agentic applications this agent is associated with.
	Applications []ApplicationReference `json:"applications"`
	// Communication protocols supported by this agent.
	Protocols []Protocol   `json:"protocols"`
	Parent    OptReference `json:"parent"`
	// Users or groups that own this agent.
	Owners []Reference `json:"owners"`
}

// GetSchemas returns the value of Schemas.
func (s *Agent) GetSchemas() []string {
	return s.Schemas
}

// GetID returns the value of ID.
func (s *Agent) GetID() OptString {
	return s.ID
}

// GetExternalId returns the value of ExternalId.
func (s *Agent) GetExternalId() OptString {
	return s.ExternalId
}

// GetMeta returns the value of Meta.
func (s *Agent) GetMeta() OptMeta {
	return s.Meta
}

// GetName returns the value of Name.
func (s *Agent) GetName() string {
	return s.Name
}

// GetDisplayName returns the value of DisplayName.
func (s *Agent) GetDisplayName() OptString {
	return s.DisplayName
}

// GetDescription returns the value of Description.
func (s *Agent) GetDescription() OptString {
	return s.Description
}

// GetAgentType returns the value of AgentType.
func (s *Agent) GetAgentType() OptString {
	return s.AgentType
}

// GetActive returns the value of Active.
func (s *Agent) GetActive() OptBool {
	return s.Active
}

// GetSubject returns the value of Subject.
func (s *Agent) GetSubject() OptString {
	return s.Subject
}

// GetGroups returns the value of Groups.
func (s *Agent) GetGroups() []GroupReference {
	return s.Groups
}

// GetEntitlements returns the value of Entitlements.
func (s *Agent) GetEntitlements() []Entitlement {
	return s.Entitlements
}

// GetRoles returns the value of Roles.
func (s *Agent) GetRoles() []Role {
	return s.Roles
}

// GetX509Certificates returns the value of X509Certificates.
func (s *Agent) GetX509Certificates() []X509Certificate {
	return s.X509Certificates
}

// GetApplications returns the value of Applications.
func (s *Agent) GetApplications() []ApplicationReference {
	return s.Applications
}

// GetProtocols returns the value of Protocols.
func (s *Agent) GetProtocols() []Protocol {
	return s.Protocols
}

// GetParent returns the value of Parent.
func (s *Agent) GetParent() OptReference {
	return s.Parent
}

// GetOwners returns the value of Owners.
func (s *Agent) GetOwners() []Reference {
	return s.Owners
}

// SetSchemas sets the value of Schemas.
func (s *Agent) SetSchemas(val []string) {
	s.Schemas = val
}

// SetID sets the value of ID.
func (s *Agent) SetID(val OptString) {
	s.ID = val
}

// SetExternalId sets the value of ExternalId.
func (s *Agent) SetExternalId(val OptString) {
	s.ExternalId = val
}

// SetMeta sets the value of Meta.
func (s *Agent) SetMeta(val OptMeta) {
	s.Meta = val
}

// SetName sets the value of Name.
func (s *Agent) SetName(val string) {
	s.Name = val
}

// SetDisplayName sets the value of DisplayName.
func (s *Agent) SetDisplayName(val OptString) {
	s.DisplayName = val
}

// SetDescription sets the value of Description.
func (s *Agent) SetDescription(val OptString) {
	s.Description = val
}

// SetAgentType sets the value of AgentType.
func (s *Agent) SetAgentType(val OptString) {
	s.AgentType = val
}

// SetActive sets the value of Active.
func (s *Agent) SetActive(val OptBool) {
	s.Active = val
}

// SetSubject sets the value of Subject.
func (s *Agent) SetSubject(val OptString) {
	s.Subject = val
}

// SetGroups sets the value of Groups.
func (s *Agent) SetGroups(val []GroupReference) {
	s.Groups = val
}

// SetEntitlements sets the value of Entitlements.
func (s *Agent) SetEntitlements(val []Entitlement) {
	s.Entitlements = val
}

// SetRoles sets the value of Roles.
func (s *Agent) SetRoles(val []Role) {
	s.Roles = val
}

// SetX509Certificates sets the value of X509Certificates.
func (s *Agent) SetX509Certificates(val []X509Certificate) {
	s.X509Certificates = val
}

// SetApplications sets the value of Applications.
func (s *Agent) SetApplications(val []ApplicationReference) {
	s.Applications = val
}

// SetProtocols sets the value of Protocols.
func (s *Agent) SetProtocols(val []Protocol) {
	s.Protocols = val
}

// SetParent sets the value of Parent.
func (s *Agent) SetParent(val OptReference) {
	s.Parent = val
}

// SetOwners sets the value of Owners.
func (s *Agent) SetOwners(val []Reference) {
	s.Owners = val
}

func (*Agent) createAgentRes()  {}
func (*Agent) getAgentRes()     {}
func (*Agent) patchAgentRes()   {}
func (*Agent) replaceAgentRes() {}

// Request body for creating or replacing an agent.
// Ref: #/components/schemas/AgentCreate
type AgentCreate struct {
	// The schemas used for this resource.
	Schemas []string `json:"schemas"`
	// An external identifier for the agent.
	ExternalId OptString `json:"externalId"`
	// The unique name of the agent. REQUIRED.
	Name string `json:"name"`
	// A human-readable display name for the agent.
	DisplayName OptString `json:"displayName"`
	// A description of the agent.
	Description OptString `json:"description"`
	// The type of agent.
	AgentType OptString `json:"agentType"`
	// Whether the agent is administratively active.
	Active OptBool `json:"active"`
	// The subject for inbound token federation correlation.
	Subject OptString `json:"subject"`
	// Entitlements granted to the agent.
	Entitlements []Entitlement `json:"entitlements"`
	// Roles assigned to the agent.
	Roles []Role `json:"roles"`
	// X.509 certificates associated with the agent.
	X509Certificates []X509Certificate `json:"x509Certificates"`
	// Communication protocols supported by this agent.
	Protocols []Protocol   `json:"protocols"`
	Parent    OptReference `json:"parent"`
	// Users or groups that own this agent.
	Owners []Reference `json:"owners"`
}

// GetSchemas returns the value of Schemas.
func (s *AgentCreate) GetSchemas() []string {
	return s.Schemas
}

// GetExternalId returns the value of ExternalId.
func (s *AgentCreate) GetExternalId() OptString {
	return s.ExternalId
}

// GetName returns the value of Name.
func (s *AgentCreate) GetName() string {
	return s.Name
}

// GetDisplayName returns the value of DisplayName.
func (s *AgentCreate) GetDisplayName() OptString {
	return s.DisplayName
}

// GetDescription returns the value of Description.
func (s *AgentCreate) GetDescription() OptString {
	return s.Description
}

// GetAgentType returns the value of AgentType.
func (s *AgentCreate) GetAgentType() OptString {
	return s.AgentType
}

// GetActive returns the value of Active.
func (s *AgentCreate) GetActive() OptBool {
	return s.Active
}

// GetSubject returns the value of Subject.
func (s *AgentCreate) GetSubject() OptString {
	return s.Subject
}

// GetEntitlements returns the value of Entitlements.
func (s *AgentCreate) GetEntitlements() []Entitlement {
	return s.Entitlements
}

// GetRoles returns the value of Roles.
func (s *AgentCreate) GetRoles() []Role {
	return s.Roles
}

// GetX509Certificates returns the value of X509Certificates.
func (s *AgentCreate) GetX509Certificates() []X509Certificate {
	return s.X509Certificates
}

// GetProtocols returns the value of Protocols.
func (s *AgentCreate) GetProtocols() []Protocol {
	return s.Protocols
}

// GetParent returns the value of Parent.
func (s *AgentCreate) GetParent() OptReference {
	return s.Parent
}

// GetOwners returns the value of Owners.
func (s *AgentCreate) GetOwners() []Reference {
	return s.Owners
}

// SetSchemas sets the value of Schemas.
func (s *AgentCreate) SetSchemas(val []string) {
	s.Schemas = val
}

// SetExternalId sets the value of ExternalId.
func (s *AgentCreate) SetExternalId(val OptString) {
	s.ExternalId = val
}

// SetName sets the value of Name.
func (s *AgentCreate) SetName(val string) {
	s.Name = val
}

// SetDisplayName sets the value of DisplayName.
func (s *AgentCreate) SetDisplayName(val OptString) {
	s.DisplayName = val
}

// SetDescription sets the value of Description.
func (s *AgentCreate) SetDescription(val OptString) {
	s.Description = val
}

// SetAgentType sets the value of AgentType.
func (s *AgentCreate) SetAgentType(val OptString) {
	s.AgentType = val
}

// SetActive sets the value of Active.
func (s *AgentCreate) SetActive(val OptBool) {
	s.Active = val
}

// SetSubject sets the value of Subject.
func (s *AgentCreate) SetSubject(val OptString) {
	s.Subject = val
}

// SetEntitlements sets the value of Entitlements.
func (s *AgentCreate) SetEntitlements(val []Entitlement) {
	s.Entitlements = val
}

// SetRoles sets the value of Roles.
func (s *AgentCreate) SetRoles(val []Role) {
	s.Roles = val
}

// SetX509Certificates sets the value of X509Certificates.
func (s *AgentCreate) SetX509Certificates(val []X509Certificate) {
	s.X509Certificates = val
}

// SetProtocols sets the value of Protocols.
func (s *AgentCreate) SetProtocols(val []Protocol) {
	s.Protocols = val
}

// SetParent sets the value of Parent.
func (s *AgentCreate) SetParent(val OptReference) {
	s.Parent = val
}

// SetOwners sets the value of Owners.
func (s *AgentCreate) SetOwners(val []Reference) {
	s.Owners = val
}

// Agent Extension configuration in ServiceProviderConfig.
// Ref: #/components/schemas/AgentExtensionConfig
type AgentExtensionConfig struct {
	// Whether any aspect of the agent extension is supported.
	Supported OptBool `json:"supported"`
	// Whether the Agent resource type is supported.
	AgentsSupported OptBool `json:"agentsSupported"`
	// Whether the AgenticApplication resource type is supported.
	AgenticApplicationsSupported OptBool `json:"agenticApplicationsSupported"`
}

// GetSupported returns the value of Supported.
func (s *AgentExtensionConfig) GetSupported() OptBool {
	return s.Supported
}

// GetAgentsSupported returns the value of AgentsSupported.
func (s *AgentExtensionConfig) GetAgentsSupported() OptBool {
	return s.AgentsSupported
}

// GetAgenticApplicationsSupported returns the value of AgenticApplicationsSupported.
func (s *AgentExtensionConfig) GetAgenticApplicationsSupported() OptBool {
	return s.AgenticApplicationsSupported
}

// SetSupported sets the value of Supported.
func (s *AgentExtensionConfig) SetSupported(val OptBool) {
	s.Supported = val
}

// SetAgentsSupported sets the value of AgentsSupported.
func (s *AgentExtensionConfig) SetAgentsSupported(val OptBool) {
	s.AgentsSupported = val
}

// SetAgenticApplicationsSupported sets the value of AgenticApplicationsSupported.
func (s *AgentExtensionConfig) SetAgenticApplicationsSupported(val OptBool) {
	s.AgenticApplicationsSupported = val
}

// SCIM list response for agents.
// Ref: #/components/schemas/AgentListResponse
type AgentListResponse struct {
	Schemas []string `json:"schemas"`
	// Total number of results matching the query.
	TotalResults int `json:"totalResults"`
	// 1-based index of the first result returned.
	StartIndex OptInt `json:"startIndex"`
	// Number of results returned in this response.
	ItemsPerPage OptInt `json:"itemsPerPage"`
	// The list of agents.
	Resources []Agent `json:"Resources"`
}

// GetSchemas returns the value of Schemas.
func (s *AgentListResponse) GetSchemas() []string {
	return s.Schemas
}

// GetTotalResults returns the value of TotalResults.
func (s *AgentListResponse) GetTotalResults() int {
	return s.TotalResults
}

// GetStartIndex returns the value of StartIndex.
func (s *AgentListResponse) GetStartIndex() OptInt {
	return s.StartIndex
}

// GetItemsPerPage returns the value of ItemsPerPage.
func (s *AgentListResponse) GetItemsPerPage() OptInt {
	return s.ItemsPerPage
}

// GetResources returns the value of Resources.
func (s *AgentListResponse) GetResources() []Agent {
	return s.Resources
}

// SetSchemas sets the value of Schemas.
func (s *AgentListResponse) SetSchemas(val []string) {
	s.Schemas = val
}

// SetTotalResults sets the value of TotalResults.
func (s *AgentListResponse) SetTotalResults(val int) {
	s.TotalResults = val
}

// SetStartIndex sets the value of StartIndex.
func (s *AgentListResponse) SetStartIndex(val OptInt) {
	s.StartIndex = val
}

// SetItemsPerPage sets the value of ItemsPerPage.
func (s *AgentListResponse) SetItemsPerPage(val OptInt) {
	s.ItemsPerPage = val
}

// SetResources sets the value of Resources.
func (s *AgentListResponse) SetResources(val []Agent) {
	s.Resources = val
}

func (*AgentListResponse) listAgentsRes() {}

// Merged schema.
// Ref: #/components/schemas/AgentReference
type AgentReference struct {
	// The identifier of the referenced resource.
	Value OptString `json:"value"`
	// The URI of the referenced resource.
	Ref OptURI `json:"$ref"`
	// A human-readable name for the referenced resource.
	Display OptString `json:"display"`
	// The relationship type between the agent and application.
	Type OptAgentReferenceType `json:"type"`
}

// GetValue returns the value of Value.
func (s *AgentReference) GetValue() OptString {
	return s.Value
}

// GetRef returns the value of Ref.
func (s *AgentReference) GetRef() OptURI {
	return s.Ref
}

// GetDisplay returns the value of Display.
func (s *AgentReference) GetDisplay() OptString {
	return s.Display
}

// GetType returns the value of Type.
func (s *AgentReference) GetType() OptAgentReferenceType {
	return s.Type
}

// SetValue sets the value of Value.
func (s *AgentReference) SetValue(val OptString) {
	s.Value = val
}

// SetRef sets the value of Ref.
func (s *AgentReference) SetRef(val OptURI) {
	s.Ref = val
}

// SetDisplay sets the value of Display.
func (s *AgentReference) SetDisplay(val OptString) {
	s.Display = val
}

// SetType sets the value of Type.
func (s *AgentReference) SetType(val OptAgentReferenceType) {
	s.Type = val
}

// The relationship type between the agent and application.
type AgentReferenceType string

const (
	AgentReferenceTypeOwned      AgentReferenceType = "owned"
	AgentReferenceTypeAuthorized AgentReferenceType = "authorized"
	AgentReferenceTypeGuest      AgentReferenceType = "guest"
)

// AllValues returns all AgentReferenceType values.
func (AgentReferenceType) AllValues() []AgentReferenceType {
	return []AgentReferenceType{
		AgentReferenceTypeOwned,
		AgentReferenceTypeAuthorized,
		AgentReferenceTypeGuest,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AgentReferenceType) MarshalText() ([]byte, error) {
	switch s {
	case AgentReferenceTypeOwned:
		return []byte(s), nil
	case AgentReferenceTypeAuthorized:
		return []byte(s), nil
	case AgentReferenceTypeGuest:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AgentReferenceType) UnmarshalText(data []byte) error {
	switch AgentReferenceType(data) {
	case AgentReferenceTypeOwned:
		*s = AgentReferenceTypeOwned
		return nil
	case AgentReferenceTypeAuthorized:
		*s = AgentReferenceTypeAuthorized
		return nil
	case AgentReferenceTypeGuest:
		*s = AgentReferenceTypeGuest
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// An application that hosts or provides access to one or more agents.
// Schema URI: urn:ietf:params:scim:schemas:core:2.0:AgenticApplication.
// Ref: #/components/schemas/AgenticApplication
type AgenticApplication struct {
	// The schemas used for this resource.
	Schemas []string `json:"schemas"`
	// The unique identifier for the agentic application.
	ID OptString `json:"id"`
	// An external identifier for the agentic application.
	ExternalId OptString `json:"externalId"`
	Meta       OptMeta   `json:"meta"`
	// The unique name of the agentic application. REQUIRED.
	Name string `json:"name"`
	// A human-readable display name for the agentic application.
	DisplayName OptString `json:"displayName"`
	// A description of the agentic application.
	Description OptString `json:"description"`
	// Whether the agentic application is administratively active.
	Active OptBool `json:"active"`
	// URLs associated with this agentic application.
	ApplicationUrls []ApplicationUrl `json:"applicationUrls"`
	// Timestamp of when the application was last accessed.
	LastAccessed OptDateTime `json:"lastAccessed"`
	// OAuth client configurations for this agentic application.
	OAuthConfiguration []OAuthConfiguration `json:"oAuthConfiguration"`
	// Agents associated with this agentic application.
	Agents []AgentReference `json:"agents"`
	// External identifiers for this agentic application.
	ExternalIdentifiers []ExternalIdentifier `json:"externalIdentifiers"`
}

// GetSchemas returns the value of Schemas.
func (s *AgenticApplication) GetSchemas() []string {
	return s.Schemas
}

// GetID returns the value of ID.
func (s *AgenticApplication) GetID() OptString {
	return s.ID
}

// GetExternalId returns the value of ExternalId.
func (s *AgenticApplication) GetExternalId() OptString {
	return s.ExternalId
}

// GetMeta returns the value of Meta.
func (s *AgenticApplication) GetMeta() OptMeta {
	return s.Meta
}

// GetName returns the value of Name.
func (s *AgenticApplication) GetName() string {
	return s.Name
}

// GetDisplayName returns the value of DisplayName.
func (s *AgenticApplication) GetDisplayName() OptString {
	return s.DisplayName
}

// GetDescription returns the value of Description.
func (s *AgenticApplication) GetDescription() OptString {
	return s.Description
}

// GetActive returns the value of Active.
func (s *AgenticApplication) GetActive() OptBool {
	return s.Active
}

// GetApplicationUrls returns the value of ApplicationUrls.
func (s *AgenticApplication) GetApplicationUrls() []ApplicationUrl {
	return s.ApplicationUrls
}

// GetLastAccessed returns the value of LastAccessed.
func (s *AgenticApplication) GetLastAccessed() OptDateTime {
	return s.LastAccessed
}

// GetOAuthConfiguration returns the value of OAuthConfiguration.
func (s *AgenticApplication) GetOAuthConfiguration() []OAuthConfiguration {
	return s.OAuthConfiguration
}

// GetAgents returns the value of Agents.
func (s *AgenticApplication) GetAgents() []AgentReference {
	return s.Agents
}

// GetExternalIdentifiers returns the value of ExternalIdentifiers.
func (s *AgenticApplication) GetExternalIdentifiers() []ExternalIdentifier {
	return s.ExternalIdentifiers
}

// SetSchemas sets the value of Schemas.
func (s *AgenticApplication) SetSchemas(val []string) {
	s.Schemas = val
}

// SetID sets the value of ID.
func (s *AgenticApplication) SetID(val OptString) {
	s.ID = val
}

// SetExternalId sets the value of ExternalId.
func (s *AgenticApplication) SetExternalId(val OptString) {
	s.ExternalId = val
}

// SetMeta sets the value of Meta.
func (s *AgenticApplication) SetMeta(val OptMeta) {
	s.Meta = val
}

// SetName sets the value of Name.
func (s *AgenticApplication) SetName(val string) {
	s.Name = val
}

// SetDisplayName sets the value of DisplayName.
func (s *AgenticApplication) SetDisplayName(val OptString) {
	s.DisplayName = val
}

// SetDescription sets the value of Description.
func (s *AgenticApplication) SetDescription(val OptString) {
	s.Description = val
}

// SetActive sets the value of Active.
func (s *AgenticApplication) SetActive(val OptBool) {
	s.Active = val
}

// SetApplicationUrls sets the value of ApplicationUrls.
func (s *AgenticApplication) SetApplicationUrls(val []ApplicationUrl) {
	s.ApplicationUrls = val
}

// SetLastAccessed sets the value of LastAccessed.
func (s *AgenticApplication) SetLastAccessed(val OptDateTime) {
	s.LastAccessed = val
}

// SetOAuthConfiguration sets the value of OAuthConfiguration.
func (s *AgenticApplication) SetOAuthConfiguration(val []OAuthConfiguration) {
	s.OAuthConfiguration = val
}

// SetAgents sets the value of Agents.
func (s *AgenticApplication) SetAgents(val []AgentReference) {
	s.Agents = val
}

// SetExternalIdentifiers sets the value of ExternalIdentifiers.
func (s *AgenticApplication) SetExternalIdentifiers(val []ExternalIdentifier) {
	s.ExternalIdentifiers = val
}

func (*AgenticApplication) createAgenticApplicationRes()  {}
func (*AgenticApplication) getAgenticApplicationRes()     {}
func (*AgenticApplication) patchAgenticApplicationRes()   {}
func (*AgenticApplication) replaceAgenticApplicationRes() {}

// Request body for creating or replacing an agentic application.
// Ref: #/components/schemas/AgenticApplicationCreate
type AgenticApplicationCreate struct {
	// The schemas used for this resource.
	Schemas []string `json:"schemas"`
	// An external identifier for the agentic application.
	ExternalId OptString `json:"externalId"`
	// The unique name of the agentic application. REQUIRED.
	Name string `json:"name"`
	// A human-readable display name for the agentic application.
	DisplayName OptString `json:"displayName"`
	// A description of the agentic application.
	Description OptString `json:"description"`
	// Whether the agentic application is administratively active.
	Active OptBool `json:"active"`
	// URLs associated with this agentic application.
	ApplicationUrls []ApplicationUrl `json:"applicationUrls"`
	// OAuth client configurations for this agentic application.
	OAuthConfiguration []OAuthConfiguration `json:"oAuthConfiguration"`
	// Agents associated with this agentic application.
	Agents []AgentReference `json:"agents"`
	// External identifiers for this agentic application.
	ExternalIdentifiers []ExternalIdentifier `json:"externalIdentifiers"`
}

// GetSchemas returns the value of Schemas.
func (s *AgenticApplicationCreate) GetSchemas() []string {
	return s.Schemas
}

// GetExternalId returns the value of ExternalId.
func (s *AgenticApplicationCreate) GetExternalId() OptString {
	return s.ExternalId
}

// GetName returns the value of Name.
func (s *AgenticApplicationCreate) GetName() string {
	return s.Name
}

// GetDisplayName returns the value of DisplayName.
func (s *AgenticApplicationCreate) GetDisplayName() OptString {
	return s.DisplayName
}

// GetDescription returns the value of Description.
func (s *AgenticApplicationCreate) GetDescription() OptString {
	return s.Description
}

// GetActive returns the value of Active.
func (s *AgenticApplicationCreate) GetActive() OptBool {
	return s.Active
}

// GetApplicationUrls returns the value of ApplicationUrls.
func (s *AgenticApplicationCreate) GetApplicationUrls() []ApplicationUrl {
	return s.ApplicationUrls
}

// GetOAuthConfiguration returns the value of OAuthConfiguration.
func (s *AgenticApplicationCreate) GetOAuthConfiguration() []OAuthConfiguration {
	return s.OAuthConfiguration
}

// GetAgents returns the value of Agents.
func (s *AgenticApplicationCreate) GetAgents() []AgentReference {
	return s.Agents
}

// GetExternalIdentifiers returns the value of ExternalIdentifiers.
func (s *AgenticApplicationCreate) GetExternalIdentifiers() []ExternalIdentifier {
	return s.ExternalIdentifiers
}

// SetSchemas sets the value of Schemas.
func (s *AgenticApplicationCreate) SetSchemas(val []string) {
	s.Schemas = val
}

// SetExternalId sets the value of ExternalId.
func (s *AgenticApplicationCreate) SetExternalId(val OptString) {
	s.ExternalId = val
}

// SetName sets the value of Name.
func (s *AgenticApplicationCreate) SetName(val string) {
	s.Name = val
}

// SetDisplayName sets the value of DisplayName.
func (s *AgenticApplicationCreate) SetDisplayName(val OptString) {
	s.DisplayName = val
}

// SetDescription sets the value of Description.
func (s *AgenticApplicationCreate) SetDescription(val OptString) {
	s.Description = val
}

// SetActive sets the value of Active.
func (s *AgenticApplicationCreate) SetActive(val OptBool) {
	s.Active = val
}

// SetApplicationUrls sets the value of ApplicationUrls.
func (s *AgenticApplicationCreate) SetApplicationUrls(val []ApplicationUrl) {
	s.ApplicationUrls = val
}

// SetOAuthConfiguration sets the value of OAuthConfiguration.
func (s *AgenticApplicationCreate) SetOAuthConfiguration(val []OAuthConfiguration) {
	s.OAuthConfiguration = val
}

// SetAgents sets the value of Agents.
func (s *AgenticApplicationCreate) SetAgents(val []AgentReference) {
	s.Agents = val
}

// SetExternalIdentifiers sets the value of ExternalIdentifiers.
func (s *AgenticApplicationCreate) SetExternalIdentifiers(val []ExternalIdentifier) {
	s.ExternalIdentifiers = val
}

// SCIM list response for agentic applications.
// Ref: #/components/schemas/AgenticApplicationListResponse
type AgenticApplicationListResponse struct {
	Schemas []string `json:"schemas"`
	// Total number of results matching the query.
	TotalResults int `json:"totalResults"`
	// 1-based index of the first result returned.
	StartIndex OptInt `json:"startIndex"`
	// Number of results returned in this response.
	ItemsPerPage OptInt `json:"itemsPerPage"`
	// The list of agentic applications.
	Resources []AgenticApplication `json:"Resources"`
}

// GetSchemas returns the value of Schemas.
func (s *AgenticApplicationListResponse) GetSchemas() []string {
	return s.Schemas
}

// GetTotalResults returns the value of TotalResults.
func (s *AgenticApplicationListResponse) GetTotalResults() int {
	return s.TotalResults
}

// GetStartIndex returns the value of StartIndex.
func (s *AgenticApplicationListResponse) GetStartIndex() OptInt {
	return s.StartIndex
}

// GetItemsPerPage returns the value of ItemsPerPage.
func (s *AgenticApplicationListResponse) GetItemsPerPage() OptInt {
	return s.ItemsPerPage
}

// GetResources returns the value of Resources.
func (s *AgenticApplicationListResponse) GetResources() []AgenticApplication {
	return s.Resources
}

// SetSchemas sets the value of Schemas.
func (s *AgenticApplicationListResponse) SetSchemas(val []string) {
	s.Schemas = val
}

// SetTotalResults sets the value of TotalResults.
func (s *AgenticApplicationListResponse) SetTotalResults(val int) {
	s.TotalResults = val
}

// SetStartIndex sets the value of StartIndex.
func (s *AgenticApplicationListResponse) SetStartIndex(val OptInt) {
	s.StartIndex = val
}

// SetItemsPerPage sets the value of ItemsPerPage.
func (s *AgenticApplicationListResponse) SetItemsPerPage(val OptInt) {
	s.ItemsPerPage = val
}

// SetResources sets the value of Resources.
func (s *AgenticApplicationListResponse) SetResources(val []AgenticApplication) {
	s.Resources = val
}

func (*AgenticApplicationListResponse) listAgenticApplicationsRes() {}

// Merged schema.
// Ref: #/components/schemas/ApplicationReference
type ApplicationReference struct {
	// The identifier of the referenced resource.
	Value OptString `json:"value"`
	// The URI of the referenced resource.
	Ref OptURI `json:"$ref"`
	// A human-readable name for the referenced resource.
	Display OptString `json:"display"`
	// The type of application.
	Type OptString `json:"type"`
}

// GetValue returns the value of Value.
func (s *ApplicationReference) GetValue() OptString {
	return s.Value
}

// GetRef returns the value of Ref.
func (s *ApplicationReference) GetRef() OptURI {
	return s.Ref
}

// GetDisplay returns the value of Display.
func (s *ApplicationReference) GetDisplay() OptString {
	return s.Display
}

// GetType returns the value of Type.
func (s *ApplicationReference) GetType() OptString {
	return s.Type
}

// SetValue sets the value of Value.
func (s *ApplicationReference) SetValue(val OptString) {
	s.Value = val
}

// SetRef sets the value of Ref.
func (s *ApplicationReference) SetRef(val OptURI) {
	s.Ref = val
}

// SetDisplay sets the value of Display.
func (s *ApplicationReference) SetDisplay(val OptString) {
	s.Display = val
}

// SetType sets the value of Type.
func (s *ApplicationReference) SetType(val OptString) {
	s.Type = val
}

// A URL associated with an agentic application.
// Ref: #/components/schemas/ApplicationUrl
type ApplicationUrl struct {
	// The type of URL.
	Type OptApplicationUrlType `json:"type"`
	// Whether this is the primary URL of this type.
	Primary OptBool `json:"primary"`
	// The URL value.
	Value OptURI `json:"value"`
	// A human-readable description of the URL.
	Description OptString `json:"description"`
}

// GetType returns the value of Type.
func (s *ApplicationUrl) GetType() OptApplicationUrlType {
	return s.Type
}

// GetPrimary returns the value of Primary.
func (s *ApplicationUrl) GetPrimary() OptBool {
	return s.Primary
}

// GetValue returns the value of Value.
func (s *ApplicationUrl) GetValue() OptURI {
	return s.Value
}

// GetDescription returns the value of Description.
func (s *ApplicationUrl) GetDescription() OptString {
	return s.Description
}

// SetType sets the value of Type.
func (s *ApplicationUrl) SetType(val OptApplicationUrlType) {
	s.Type = val
}

// SetPrimary sets the value of Primary.
func (s *ApplicationUrl) SetPrimary(val OptBool) {
	s.Primary = val
}

// SetValue sets the value of Value.
func (s *ApplicationUrl) SetValue(val OptURI) {
	s.Value = val
}

// SetDescription sets the value of Description.
func (s *ApplicationUrl) SetDescription(val OptString) {
	s.Description = val
}

// The type of URL.
type ApplicationUrlType string

const (
	ApplicationUrlTypeSsoEndpoint ApplicationUrlType = "ssoEndpoint"
	ApplicationUrlTypeLoginPage   ApplicationUrlType = "loginPage"
	ApplicationUrlTypeAPI         ApplicationUrlType = "api"
	ApplicationUrlTypeHomepage    ApplicationUrlType = "homepage"
)

// AllValues returns all ApplicationUrlType values.
func (ApplicationUrlType) AllValues() []ApplicationUrlType {
	return []ApplicationUrlType{
		ApplicationUrlTypeSsoEndpoint,
		ApplicationUrlTypeLoginPage,
		ApplicationUrlTypeAPI,
		ApplicationUrlTypeHomepage,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ApplicationUrlType) MarshalText() ([]byte, error) {
	switch s {
	case ApplicationUrlTypeSsoEndpoint:
		return []byte(s), nil
	case ApplicationUrlTypeLoginPage:
		return []byte(s), nil
	case ApplicationUrlTypeAPI:
		return []byte(s), nil
	case ApplicationUrlTypeHomepage:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ApplicationUrlType) UnmarshalText(data []byte) error {
	switch ApplicationUrlType(data) {
	case ApplicationUrlTypeSsoEndpoint:
		*s = ApplicationUrlTypeSsoEndpoint
		return nil
	case ApplicationUrlTypeLoginPage:
		*s = ApplicationUrlTypeLoginPage
		return nil
	case ApplicationUrlTypeAPI:
		*s = ApplicationUrlTypeAPI
		return nil
	case ApplicationUrlTypeHomepage:
		*s = ApplicationUrlTypeHomepage
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

type CreateAgentBadRequest Error

func (*CreateAgentBadRequest) createAgentRes() {}

type CreateAgentConflict Error

func (*CreateAgentConflict) createAgentRes() {}

type CreateAgentForbidden Error

func (*CreateAgentForbidden) createAgentRes() {}

type CreateAgentInternalServerError Error

func (*CreateAgentInternalServerError) createAgentRes() {}

type CreateAgentUnauthorized Error

func (*CreateAgentUnauthorized) createAgentRes() {}

type CreateAgenticApplicationBadRequest Error

func (*CreateAgenticApplicationBadRequest) createAgenticApplicationRes() {}

type CreateAgenticApplicationConflict Error

func (*CreateAgenticApplicationConflict) createAgenticApplicationRes() {}

type CreateAgenticApplicationForbidden Error

func (*CreateAgenticApplicationForbidden) createAgenticApplicationRes() {}

type CreateAgenticApplicationInternalServerError Error

func (*CreateAgenticApplicationInternalServerError) createAgenticApplicationRes() {}

type CreateAgenticApplicationUnauthorized Error

func (*CreateAgenticApplicationUnauthorized) createAgenticApplicationRes() {}

type DeleteAgentForbidden Error

func (*DeleteAgentForbidden) deleteAgentRes() {}

type DeleteAgentInternalServerError Error

func (*DeleteAgentInternalServerError) deleteAgentRes() {}

// DeleteAgentNoContent is response for DeleteAgent operation.
type DeleteAgentNoContent struct{}

func (*DeleteAgentNoContent) deleteAgentRes() {}

type DeleteAgentNotFound Error

func (*DeleteAgentNotFound) deleteAgentRes() {}

type DeleteAgentUnauthorized Error

func (*DeleteAgentUnauthorized) deleteAgentRes() {}

type DeleteAgenticApplicationForbidden Error

func (*DeleteAgenticApplicationForbidden) deleteAgenticApplicationRes() {}

type DeleteAgenticApplicationInternalServerError Error

func (*DeleteAgenticApplicationInternalServerError) deleteAgenticApplicationRes() {}

// DeleteAgenticApplicationNoContent is response for DeleteAgenticApplication operation.
type DeleteAgenticApplicationNoContent struct{}

func (*DeleteAgenticApplicationNoContent) deleteAgenticApplicationRes() {}

type DeleteAgenticApplicationNotFound Error

func (*DeleteAgenticApplicationNotFound) deleteAgenticApplicationRes() {}

type DeleteAgenticApplicationUnauthorized Error

func (*DeleteAgenticApplicationUnauthorized) deleteAgenticApplicationRes() {}

// An entitlement granted to an agent.
// Ref: #/components/schemas/Entitlement
type Entitlement struct {
	// The value of the entitlement.
	Value OptString `json:"value"`
	// A human-readable name for the entitlement.
	Display OptString `json:"display"`
	// A label indicating the entitlement's function.
	Type OptString `json:"type"`
	// Whether this is the primary entitlement.
	Primary OptBool `json:"primary"`
}

// GetValue returns the value of Value.
func (s *Entitlement) GetValue() OptString {
	return s.Value
}

// GetDisplay returns the value of Display.
func (s *Entitlement) GetDisplay() OptString {
	return s.Display
}

// GetType returns the value of Type.
func (s *Entitlement) GetType() OptString {
	return s.Type
}

// GetPrimary returns the value of Primary.
func (s *Entitlement) GetPrimary() OptBool {
	return s.Primary
}

// SetValue sets the value of Value.
func (s *Entitlement) SetValue(val OptString) {
	s.Value = val
}

// SetDisplay sets the value of Display.
func (s *Entitlement) SetDisplay(val OptString) {
	s.Display = val
}

// SetType sets the value of Type.
func (s *Entitlement) SetType(val OptString) {
	s.Type = val
}

// SetPrimary sets the value of Primary.
func (s *Entitlement) SetPrimary(val OptBool) {
	s.Primary = val
}

// SCIM error response.
// Ref: #/components/schemas/Error
type Error struct {
	Schemas []string `json:"schemas"`
	// The HTTP status code as a string.
	Status string `json:"status"`
	// A SCIM-specific error type.
	ScimType OptErrorScimType `json:"scimType"`
	// A detailed error message.
	Detail OptString `json:"detail"`
}

// GetSchemas returns the value of Schemas.
func (s *Error) GetSchemas() []string {
	return s.Schemas
}

// GetStatus returns the value of Status.
func (s *Error) GetStatus() string {
	return s.Status
}

// GetScimType returns the value of ScimType.
func (s *Error) GetScimType() OptErrorScimType {
	return s.ScimType
}

// GetDetail returns the value of Detail.
func (s *Error) GetDetail() OptString {
	return s.Detail
}

// SetSchemas sets the value of Schemas.
func (s *Error) SetSchemas(val []string) {
	s.Schemas = val
}

// SetStatus sets the value of Status.
func (s *Error) SetStatus(val string) {
	s.Status = val
}

// SetScimType sets the value of ScimType.
func (s *Error) SetScimType(val OptErrorScimType) {
	s.ScimType = val
}

// SetDetail sets the value of Detail.
func (s *Error) SetDetail(val OptString) {
	s.Detail = val
}

func (*Error) getServiceProviderConfigRes() {}

// A SCIM-specific error type.
type ErrorScimType string

const (
	ErrorScimTypeInvalidFilter ErrorScimType = "invalidFilter"
	ErrorScimTypeTooMany       ErrorScimType = "tooMany"
	ErrorScimTypeUniqueness    ErrorScimType = "uniqueness"
	ErrorScimTypeMutability    ErrorScimType = "mutability"
	ErrorScimTypeInvalidSyntax ErrorScimType = "invalidSyntax"
	ErrorScimTypeInvalidPath   ErrorScimType = "invalidPath"
	ErrorScimTypeNoTarget      ErrorScimType = "noTarget"
	ErrorScimTypeInvalidValue  ErrorScimType = "invalidValue"
	ErrorScimTypeInvalidVers   ErrorScimType = "invalidVers"
	ErrorScimTypeSensitive     ErrorScimType = "sensitive"
)

// AllValues returns all ErrorScimType values.
func (ErrorScimType) AllValues() []ErrorScimType {
	return []ErrorScimType{
		ErrorScimTypeInvalidFilter,
		ErrorScimTypeTooMany,
		ErrorScimTypeUniqueness,
		ErrorScimTypeMutability,
		ErrorScimTypeInvalidSyntax,
		ErrorScimTypeInvalidPath,
		ErrorScimTypeNoTarget,
		ErrorScimTypeInvalidValue,
		ErrorScimTypeInvalidVers,
		ErrorScimTypeSensitive,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ErrorScimType) MarshalText() ([]byte, error) {
	switch s {
	case ErrorScimTypeInvalidFilter:
		return []byte(s), nil
	case ErrorScimTypeTooMany:
		return []byte(s), nil
	case ErrorScimTypeUniqueness:
		return []byte(s), nil
	case ErrorScimTypeMutability:
		return []byte(s), nil
	case ErrorScimTypeInvalidSyntax:
		return []byte(s), nil
	case ErrorScimTypeInvalidPath:
		return []byte(s), nil
	case ErrorScimTypeNoTarget:
		return []byte(s), nil
	case ErrorScimTypeInvalidValue:
		return []byte(s), nil
	case ErrorScimTypeInvalidVers:
		return []byte(s), nil
	case ErrorScimTypeSensitive:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ErrorScimType) UnmarshalText(data []byte) error {
	switch ErrorScimType(data) {
	case ErrorScimTypeInvalidFilter:
		*s = ErrorScimTypeInvalidFilter
		return nil
	case ErrorScimTypeTooMany:
		*s = ErrorScimTypeTooMany
		return nil
	case ErrorScimTypeUniqueness:
		*s = ErrorScimTypeUniqueness
		return nil
	case ErrorScimTypeMutability:
		*s = ErrorScimTypeMutability
		return nil
	case ErrorScimTypeInvalidSyntax:
		*s = ErrorScimTypeInvalidSyntax
		return nil
	case ErrorScimTypeInvalidPath:
		*s = ErrorScimTypeInvalidPath
		return nil
	case ErrorScimTypeNoTarget:
		*s = ErrorScimTypeNoTarget
		return nil
	case ErrorScimTypeInvalidValue:
		*s = ErrorScimTypeInvalidValue
		return nil
	case ErrorScimTypeInvalidVers:
		*s = ErrorScimTypeInvalidVers
		return nil
	case ErrorScimTypeSensitive:
		*s = ErrorScimTypeSensitive
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// An external identifier for an agentic application.
// Ref: #/components/schemas/ExternalIdentifier
type ExternalIdentifier struct {
	// The type of identifier.
	Type OptString `json:"type"`
	// The identifier value.
	Value OptString `json:"value"`
	// The system or domain within which the identifier is valid.
	System OptString `json:"system"`
}

// GetType returns the value of Type.
func (s *ExternalIdentifier) GetType() OptString {
	return s.Type
}

// GetValue returns the value of Value.
func (s *ExternalIdentifier) GetValue() OptString {
	return s.Value
}

// GetSystem returns the value of System.
func (s *ExternalIdentifier) GetSystem() OptString {
	return s.System
}

// SetType sets the value of Type.
func (s *ExternalIdentifier) SetType(val OptString) {
	s.Type = val
}

// SetValue sets the value of Value.
func (s *ExternalIdentifier) SetValue(val OptString) {
	s.Value = val
}

// SetSystem sets the value of System.
func (s *ExternalIdentifier) SetSystem(val OptString) {
	s.System = val
}

type GetAgentForbidden Error

func (*GetAgentForbidden) getAgentRes() {}

type GetAgentInternalServerError Error

func (*GetAgentInternalServerError) getAgentRes() {}

type GetAgentNotFound Error

func (*GetAgentNotFound) getAgentRes() {}

type GetAgentUnauthorized Error

func (*GetAgentUnauthorized) getAgentRes() {}

type GetAgenticApplicationForbidden Error

func (*GetAgenticApplicationForbidden) getAgenticApplicationRes() {}

type GetAgenticApplicationInternalServerError Error

func (*GetAgenticApplicationInternalServerError) getAgenticApplicationRes() {}

type GetAgenticApplicationNotFound Error

func (*GetAgenticApplicationNotFound) getAgenticApplicationRes() {}

type GetAgenticApplicationUnauthorized Error

func (*GetAgenticApplicationUnauthorized) getAgenticApplicationRes() {}

// Merged schema.
// Ref: #/components/schemas/GroupReference
type GroupReference struct {
	// The identifier of the referenced resource.
	Value OptString `json:"value"`
	// The URI of the referenced resource.
	Ref OptURI `json:"$ref"`
	// A human-readable name for the referenced resource.
	Display OptString `json:"display"`
	// The type of group membership.
	Type OptGroupReferenceType `json:"type"`
}

// GetValue returns the value of Value.
func (s *GroupReference) GetValue() OptString {
	return s.Value
}

// GetRef returns the value of Ref.
func (s *GroupReference) GetRef() OptURI {
	return s.Ref
}

// GetDisplay returns the value of Display.
func (s *GroupReference) GetDisplay() OptString {
	return s.Display
}

// GetType returns the value of Type.
func (s *GroupReference) GetType() OptGroupReferenceType {
	return s.Type
}

// SetValue sets the value of Value.
func (s *GroupReference) SetValue(val OptString) {
	s.Value = val
}

// SetRef sets the value of Ref.
func (s *GroupReference) SetRef(val OptURI) {
	s.Ref = val
}

// SetDisplay sets the value of Display.
func (s *GroupReference) SetDisplay(val OptString) {
	s.Display = val
}

// SetType sets the value of Type.
func (s *GroupReference) SetType(val OptGroupReferenceType) {
	s.Type = val
}

// The type of group membership.
type GroupReferenceType string

const (
	GroupReferenceTypeDirect   GroupReferenceType = "direct"
	GroupReferenceTypeIndirect GroupReferenceType = "indirect"
)

// AllValues returns all GroupReferenceType values.
func (GroupReferenceType) AllValues() []GroupReferenceType {
	return []GroupReferenceType{
		GroupReferenceTypeDirect,
		GroupReferenceTypeIndirect,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s GroupReferenceType) MarshalText() ([]byte, error) {
	switch s {
	case GroupReferenceTypeDirect:
		return []byte(s), nil
	case GroupReferenceTypeIndirect:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *GroupReferenceType) UnmarshalText(data []byte) error {
	switch GroupReferenceType(data) {
	case GroupReferenceTypeDirect:
		*s = GroupReferenceTypeDirect
		return nil
	case GroupReferenceTypeIndirect:
		*s = GroupReferenceTypeIndirect
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ListAgenticApplicationsBadRequest Error

func (*ListAgenticApplicationsBadRequest) listAgenticApplicationsRes() {}

type ListAgenticApplicationsForbidden Error

func (*ListAgenticApplicationsForbidden) listAgenticApplicationsRes() {}

type ListAgenticApplicationsInternalServerError Error

func (*ListAgenticApplicationsInternalServerError) listAgenticApplicationsRes() {}

type ListAgenticApplicationsUnauthorized Error

func (*ListAgenticApplicationsUnauthorized) listAgenticApplicationsRes() {}

type ListAgentsBadRequest Error

func (*ListAgentsBadRequest) listAgentsRes() {}

type ListAgentsForbidden Error

func (*ListAgentsForbidden) listAgentsRes() {}

type ListAgentsInternalServerError Error

func (*ListAgentsInternalServerError) listAgentsRes() {}

type ListAgentsUnauthorized Error

func (*ListAgentsUnauthorized) listAgentsRes() {}

// SCIM resource metadata.
// Ref: #/components/schemas/Meta
type Meta struct {
	// The name of the resource type.
	ResourceType OptString `json:"resourceType"`
	// The date and time the resource was created.
	Created OptDateTime `json:"created"`
	// The date and time the resource was last modified.
	LastModified OptDateTime `json:"lastModified"`
	// The URI of the resource.
	Location OptURI `json:"location"`
	// The version of the resource (ETag).
	Version OptString `json:"version"`
}

// GetResourceType returns the value of ResourceType.
func (s *Meta) GetResourceType() OptString {
	return s.ResourceType
}

// GetCreated returns the value of Created.
func (s *Meta) GetCreated() OptDateTime {
	return s.Created
}

// GetLastModified returns the value of LastModified.
func (s *Meta) GetLastModified() OptDateTime {
	return s.LastModified
}

// GetLocation returns the value of Location.
func (s *Meta) GetLocation() OptURI {
	return s.Location
}

// GetVersion returns the value of Version.
func (s *Meta) GetVersion() OptString {
	return s.Version
}

// SetResourceType sets the value of ResourceType.
func (s *Meta) SetResourceType(val OptString) {
	s.ResourceType = val
}

// SetCreated sets the value of Created.
func (s *Meta) SetCreated(val OptDateTime) {
	s.Created = val
}

// SetLastModified sets the value of LastModified.
func (s *Meta) SetLastModified(val OptDateTime) {
	s.LastModified = val
}

// SetLocation sets the value of Location.
func (s *Meta) SetLocation(val OptURI) {
	s.Location = val
}

// SetVersion sets the value of Version.
func (s *Meta) SetVersion(val OptString) {
	s.Version = val
}

// OAuth client configuration for an agentic application.
// Ref: #/components/schemas/OAuthConfiguration
type OAuthConfiguration struct {
	// The OAuth client identifier.
	ClientId OptString `json:"clientId"`
	// A human-readable description of the OAuth client.
	Description OptString `json:"description"`
	// The OAuth audience URI.
	AudienceUri OptURI `json:"audienceUri"`
	// The identity provider issuer URI.
	IssuerUri OptURI `json:"issuerUri"`
	// Authorized redirect URIs for the OAuth client.
	RedirectUri []url.URL `json:"redirectUri"`
}

// GetClientId returns the value of ClientId.
func (s *OAuthConfiguration) GetClientId() OptString {
	return s.ClientId
}

// GetDescription returns the value of Description.
func (s *OAuthConfiguration) GetDescription() OptString {
	return s.Description
}

// GetAudienceUri returns the value of AudienceUri.
func (s *OAuthConfiguration) GetAudienceUri() OptURI {
	return s.AudienceUri
}

// GetIssuerUri returns the value of IssuerUri.
func (s *OAuthConfiguration) GetIssuerUri() OptURI {
	return s.IssuerUri
}

// GetRedirectUri returns the value of RedirectUri.
func (s *OAuthConfiguration) GetRedirectUri() []url.URL {
	return s.RedirectUri
}

// SetClientId sets the value of ClientId.
func (s *OAuthConfiguration) SetClientId(val OptString) {
	s.ClientId = val
}

// SetDescription sets the value of Description.
func (s *OAuthConfiguration) SetDescription(val OptString) {
	s.Description = val
}

// SetAudienceUri sets the value of AudienceUri.
func (s *OAuthConfiguration) SetAudienceUri(val OptURI) {
	s.AudienceUri = val
}

// SetIssuerUri sets the value of IssuerUri.
func (s *OAuthConfiguration) SetIssuerUri(val OptURI) {
	s.IssuerUri = val
}

// SetRedirectUri sets the value of RedirectUri.
func (s *OAuthConfiguration) SetRedirectUri(val []url.URL) {
	s.RedirectUri = val
}

// NewOptAgentExtensionConfig returns new OptAgentExtensionConfig with value set to v.
func NewOptAgentExtensionConfig(v AgentExtensionConfig) OptAgentExtensionConfig {
	return OptAgentExtensionConfig{
		Value: v,
		Set:   true,
	}
}

// OptAgentExtensionConfig is optional AgentExtensionConfig.
type OptAgentExtensionConfig struct {
	Value AgentExtensionConfig
	Set   bool
}

// IsSet returns true if OptAgentExtensionConfig was set.
func (o OptAgentExtensionConfig) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAgentExtensionConfig) Reset() {
	var v AgentExtensionConfig
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAgentExtensionConfig) SetTo(v AgentExtensionConfig) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAgentExtensionConfig) Get() (v AgentExtensionConfig, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAgentExtensionConfig) Or(d AgentExtensionConfig) AgentExtensionConfig {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAgentReferenceType returns new OptAgentReferenceType with value set to v.
func NewOptAgentReferenceType(v AgentReferenceType) OptAgentReferenceType {
	return OptAgentReferenceType{
		Value: v,
		Set:   true,
	}
}

// OptAgentReferenceType is optional AgentReferenceType.
type OptAgentReferenceType struct {
	Value AgentReferenceType
	Set   bool
}

// IsSet returns true if OptAgentReferenceType was set.
func (o OptAgentReferenceType) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAgentReferenceType) Reset() {
	var v AgentReferenceType
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAgentReferenceType) SetTo(v AgentReferenceType) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAgentReferenceType) Get() (v AgentReferenceType, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAgentReferenceType) Or(d AgentReferenceType) AgentReferenceType {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptApplicationUrlType returns new OptApplicationUrlType with value set to v.
func NewOptApplicationUrlType(v ApplicationUrlType) OptApplicationUrlType {
	return OptApplicationUrlType{
		Value: v,
		Set:   true,
	}
}

// OptApplicationUrlType is optional ApplicationUrlType.
type OptApplicationUrlType struct {
	Value ApplicationUrlType
	Set   bool
}

// IsSet returns true if OptApplicationUrlType was set.
func (o OptApplicationUrlType) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptApplicationUrlType) Reset() {
	var v ApplicationUrlType
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptApplicationUrlType) SetTo(v ApplicationUrlType) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptApplicationUrlType) Get() (v ApplicationUrlType, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptApplicationUrlType) Or(d ApplicationUrlType) ApplicationUrlType {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptErrorScimType returns new OptErrorScimType with value set to v.
func NewOptErrorScimType(v ErrorScimType) OptErrorScimType {
	return OptErrorScimType{
		Value: v,
		Set:   true,
	}
}

// OptErrorScimType is optional ErrorScimType.
type OptErrorScimType struct {
	Value ErrorScimType
	Set   bool
}

// IsSet returns true if OptErrorScimType was set.
func (o OptErrorScimType) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptErrorScimType) Reset() {
	var v ErrorScimType
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptErrorScimType) SetTo(v ErrorScimType) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptErrorScimType) Get() (v ErrorScimType, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptErrorScimType) Or(d ErrorScimType) ErrorScimType {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptGroupReferenceType returns new OptGroupReferenceType with value set to v.
func NewOptGroupReferenceType(v GroupReferenceType) OptGroupReferenceType {
	return OptGroupReferenceType{
		Value: v,
		Set:   true,
	}
}

// OptGroupReferenceType is optional GroupReferenceType.
type OptGroupReferenceType struct {
	Value GroupReferenceType
	Set   bool
}

// IsSet returns true if OptGroupReferenceType was set.
func (o OptGroupReferenceType) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptGroupReferenceType) Reset() {
	var v GroupReferenceType
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptGroupReferenceType) SetTo(v GroupReferenceType) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptGroupReferenceType) Get() (v GroupReferenceType, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptGroupReferenceType) Or(d GroupReferenceType) GroupReferenceType {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptMeta returns new OptMeta with value set to v.
func NewOptMeta(v Meta) OptMeta {
	return OptMeta{
		Value: v,
		Set:   true,
	}
}

// OptMeta is optional Meta.
type OptMeta struct {
	Value Meta
	Set   bool
}

// IsSet returns true if OptMeta was set.
func (o OptMeta) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptMeta) Reset() {
	var v Meta
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptMeta) SetTo(v Meta) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptMeta) Get() (v Meta, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptMeta) Or(d Meta) Meta {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptProtocolType returns new OptProtocolType with value set to v.
func NewOptProtocolType(v ProtocolType) OptProtocolType {
	return OptProtocolType{
		Value: v,
		Set:   true,
	}
}

// OptProtocolType is optional ProtocolType.
type OptProtocolType struct {
	Value ProtocolType
	Set   bool
}

// IsSet returns true if OptProtocolType was set.
func (o OptProtocolType) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptProtocolType) Reset() {
	var v ProtocolType
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptProtocolType) SetTo(v ProtocolType) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptProtocolType) Get() (v ProtocolType, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptProtocolType) Or(d ProtocolType) ProtocolType {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptReference returns new OptReference with value set to v.
func NewOptReference(v Reference) OptReference {
	return OptReference{
		Value: v,
		Set:   true,
	}
}

// OptReference is optional Reference.
type OptReference struct {
	Value Reference
	Set   bool
}

// IsSet returns true if OptReference was set.
func (o OptReference) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptReference) Reset() {
	var v Reference
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptReference) SetTo(v Reference) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptReference) Get() (v Reference, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptReference) Or(d Reference) Reference {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptServiceProviderConfigBulk returns new OptServiceProviderConfigBulk with value set to v.
func NewOptServiceProviderConfigBulk(v ServiceProviderConfigBulk) OptServiceProviderConfigBulk {
	return OptServiceProviderConfigBulk{
		Value: v,
		Set:   true,
	}
}

// OptServiceProviderConfigBulk is optional ServiceProviderConfigBulk.
type OptServiceProviderConfigBulk struct {
	Value ServiceProviderConfigBulk
	Set   bool
}

// IsSet returns true if OptServiceProviderConfigBulk was set.
func (o OptServiceProviderConfigBulk) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptServiceProviderConfigBulk) Reset() {
	var v ServiceProviderConfigBulk
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptServiceProviderConfigBulk) SetTo(v ServiceProviderConfigBulk) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptServiceProviderConfigBulk) Get() (v ServiceProviderConfigBulk, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptServiceProviderConfigBulk) Or(d ServiceProviderConfigBulk) ServiceProviderConfigBulk {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptServiceProviderConfigChangePassword returns new OptServiceProviderConfigChangePassword with value set to v.
func NewOptServiceProviderConfigChangePassword(v ServiceProviderConfigChangePassword) OptServiceProviderConfigChangePassword {
	return OptServiceProviderConfigChangePassword{
		Value: v,
		Set:   true,
	}
}

// OptServiceProviderConfigChangePassword is optional ServiceProviderConfigChangePassword.
type OptServiceProviderConfigChangePassword struct {
	Value ServiceProviderConfigChangePassword
	Set   bool
}

// IsSet returns true if OptServiceProviderConfigChangePassword was set.
func (o OptServiceProviderConfigChangePassword) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptServiceProviderConfigChangePassword) Reset() {
	var v ServiceProviderConfigChangePassword
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptServiceProviderConfigChangePassword) SetTo(v ServiceProviderConfigChangePassword) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptServiceProviderConfigChangePassword) Get() (v ServiceProviderConfigChangePassword, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptServiceProviderConfigChangePassword) Or(d ServiceProviderConfigChangePassword) ServiceProviderConfigChangePassword {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptServiceProviderConfigEtag returns new OptServiceProviderConfigEtag with value set to v.
func NewOptServiceProviderConfigEtag(v ServiceProviderConfigEtag) OptServiceProviderConfigEtag {
	return OptServiceProviderConfigEtag{
		Value: v,
		Set:   true,
	}
}

// OptServiceProviderConfigEtag is optional ServiceProviderConfigEtag.
type OptServiceProviderConfigEtag struct {
	Value ServiceProviderConfigEtag
	Set   bool
}

// IsSet returns true if OptServiceProviderConfigEtag was set.
func (o OptServiceProviderConfigEtag) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptServiceProviderConfigEtag) Reset() {
	var v ServiceProviderConfigEtag
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptServiceProviderConfigEtag) SetTo(v ServiceProviderConfigEtag) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptServiceProviderConfigEtag) Get() (v ServiceProviderConfigEtag, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptServiceProviderConfigEtag) Or(d ServiceProviderConfigEtag) ServiceProviderConfigEtag {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptServiceProviderConfigFilter returns new OptServiceProviderConfigFilter with value set to v.
func NewOptServiceProviderConfigFilter(v ServiceProviderConfigFilter) OptServiceProviderConfigFilter {
	return OptServiceProviderConfigFilter{
		Value: v,
		Set:   true,
	}
}

// OptServiceProviderConfigFilter is optional ServiceProviderConfigFilter.
type OptServiceProviderConfigFilter struct {
	Value ServiceProviderConfigFilter
	Set   bool
}

// IsSet returns true if OptServiceProviderConfigFilter was set.
func (o OptServiceProviderConfigFilter) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptServiceProviderConfigFilter) Reset() {
	var v ServiceProviderConfigFilter
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptServiceProviderConfigFilter) SetTo(v ServiceProviderConfigFilter) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptServiceProviderConfigFilter) Get() (v ServiceProviderConfigFilter, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptServiceProviderConfigFilter) Or(d ServiceProviderConfigFilter) ServiceProviderConfigFilter {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptServiceProviderConfigPatch returns new OptServiceProviderConfigPatch with value set to v.
func NewOptServiceProviderConfigPatch(v ServiceProviderConfigPatch) OptServiceProviderConfigPatch {
	return OptServiceProviderConfigPatch{
		Value: v,
		Set:   true,
	}
}

// OptServiceProviderConfigPatch is optional ServiceProviderConfigPatch.
type OptServiceProviderConfigPatch struct {
	Value ServiceProviderConfigPatch
	Set   bool
}

// IsSet returns true if OptServiceProviderConfigPatch was set.
func (o OptServiceProviderConfigPatch) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptServiceProviderConfigPatch) Reset() {
	var v ServiceProviderConfigPatch
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptServiceProviderConfigPatch) SetTo(v ServiceProviderConfigPatch) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptServiceProviderConfigPatch) Get() (v ServiceProviderConfigPatch, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptServiceProviderConfigPatch) Or(d ServiceProviderConfigPatch) ServiceProviderConfigPatch {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptServiceProviderConfigSort returns new OptServiceProviderConfigSort with value set to v.
func NewOptServiceProviderConfigSort(v ServiceProviderConfigSort) OptServiceProviderConfigSort {
	return OptServiceProviderConfigSort{
		Value: v,
		Set:   true,
	}
}

// OptServiceProviderConfigSort is optional ServiceProviderConfigSort.
type OptServiceProviderConfigSort struct {
	Value ServiceProviderConfigSort
	Set   bool
}

// IsSet returns true if OptServiceProviderConfigSort was set.
func (o OptServiceProviderConfigSort) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptServiceProviderConfigSort) Reset() {
	var v ServiceProviderConfigSort
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptServiceProviderConfigSort) SetTo(v ServiceProviderConfigSort) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptServiceProviderConfigSort) Get() (v ServiceProviderConfigSort, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptServiceProviderConfigSort) Or(d ServiceProviderConfigSort) ServiceProviderConfigSort {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSortOrder returns new OptSortOrder with value set to v.
func NewOptSortOrder(v SortOrder) OptSortOrder {
	return OptSortOrder{
		Value: v,
		Set:   true,
	}
}

// OptSortOrder is optional SortOrder.
type OptSortOrder struct {
	Value SortOrder
	Set   bool
}

// IsSet returns true if OptSortOrder was set.
func (o OptSortOrder) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSortOrder) Reset() {
	var v SortOrder
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSortOrder) SetTo(v SortOrder) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSortOrder) Get() (v SortOrder, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSortOrder) Or(d SortOrder) SortOrder {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptURI returns new OptURI with value set to v.
func NewOptURI(v url.URL) OptURI {
	return OptURI{
		Value: v,
		Set:   true,
	}
}

// OptURI is optional url.URL.
type OptURI struct {
	Value url.URL
	Set   bool
}

// IsSet returns true if OptURI was set.
func (o OptURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptURI) SetTo(v url.URL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptURI) Get() (v url.URL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type PatchAgentBadRequest Error

func (*PatchAgentBadRequest) patchAgentRes() {}

type PatchAgentForbidden Error

func (*PatchAgentForbidden) patchAgentRes() {}

type PatchAgentInternalServerError Error

func (*PatchAgentInternalServerError) patchAgentRes() {}

type PatchAgentNotFound Error

func (*PatchAgentNotFound) patchAgentRes() {}

type PatchAgentUnauthorized Error

func (*PatchAgentUnauthorized) patchAgentRes() {}

type PatchAgenticApplicationBadRequest Error

func (*PatchAgenticApplicationBadRequest) patchAgenticApplicationRes() {}

type PatchAgenticApplicationForbidden Error

func (*PatchAgenticApplicationForbidden) patchAgenticApplicationRes() {}

type PatchAgenticApplicationInternalServerError Error

func (*PatchAgenticApplicationInternalServerError) patchAgenticApplicationRes() {}

type PatchAgenticApplicationNotFound Error

func (*PatchAgenticApplicationNotFound) patchAgenticApplicationRes() {}

type PatchAgenticApplicationUnauthorized Error

func (*PatchAgenticApplicationUnauthorized) patchAgenticApplicationRes() {}

// A single SCIM PATCH operation.
// Ref: #/components/schemas/PatchOperation
type PatchOperation struct {
	// The operation to perform.
	Op PatchOperationOp `json:"op"`
	// The attribute path to operate on.
	Path OptString `json:"path"`
	// The value to use for the operation.
	Value jx.Raw `json:"value"`
}

// GetOp returns the value of Op.
func (s *PatchOperation) GetOp() PatchOperationOp {
	return s.Op
}

// GetPath returns the value of Path.
func (s *PatchOperation) GetPath() OptString {
	return s.Path
}

// GetValue returns the value of Value.
func (s *PatchOperation) GetValue() jx.Raw {
	return s.Value
}

// SetOp sets the value of Op.
func (s *PatchOperation) SetOp(val PatchOperationOp) {
	s.Op = val
}

// SetPath sets the value of Path.
func (s *PatchOperation) SetPath(val OptString) {
	s.Path = val
}

// SetValue sets the value of Value.
func (s *PatchOperation) SetValue(val jx.Raw) {
	s.Value = val
}

// The operation to perform.
type PatchOperationOp string

const (
	PatchOperationOpAdd     PatchOperationOp = "add"
	PatchOperationOpRemove  PatchOperationOp = "remove"
	PatchOperationOpReplace PatchOperationOp = "replace"
)

// AllValues returns all PatchOperationOp values.
func (PatchOperationOp) AllValues() []PatchOperationOp {
	return []PatchOperationOp{
		PatchOperationOpAdd,
		PatchOperationOpRemove,
		PatchOperationOpReplace,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PatchOperationOp) MarshalText() ([]byte, error) {
	switch s {
	case PatchOperationOpAdd:
		return []byte(s), nil
	case PatchOperationOpRemove:
		return []byte(s), nil
	case PatchOperationOpReplace:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PatchOperationOp) UnmarshalText(data []byte) error {
	switch PatchOperationOp(data) {
	case PatchOperationOpAdd:
		*s = PatchOperationOpAdd
		return nil
	case PatchOperationOpRemove:
		*s = PatchOperationOpRemove
		return nil
	case PatchOperationOpReplace:
		*s = PatchOperationOpReplace
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// SCIM PATCH request.
// Ref: #/components/schemas/PatchRequest
type PatchRequest struct {
	Schemas []string `json:"schemas"`
	// The list of patch operations to perform.
	Operations []PatchOperation `json:"Operations"`
}

// GetSchemas returns the value of Schemas.
func (s *PatchRequest) GetSchemas() []string {
	return s.Schemas
}

// GetOperations returns the value of Operations.
func (s *PatchRequest) GetOperations() []PatchOperation {
	return s.Operations
}

// SetSchemas sets the value of Schemas.
func (s *PatchRequest) SetSchemas(val []string) {
	s.Schemas = val
}

// SetOperations sets the value of Operations.
func (s *PatchRequest) SetOperations(val []PatchOperation) {
	s.Operations = val
}

// A communication protocol supported by an agent.
// Ref: #/components/schemas/Protocol
type Protocol struct {
	// The type of protocol.
	Type OptProtocolType `json:"type"`
	// The URL of the specification document for this protocol.
	SpecificationUrl OptURI `json:"specificationUrl"`
}

// GetType returns the value of Type.
func (s *Protocol) GetType() OptProtocolType {
	return s.Type
}

// GetSpecificationUrl returns the value of SpecificationUrl.
func (s *Protocol) GetSpecificationUrl() OptURI {
	return s.SpecificationUrl
}

// SetType sets the value of Type.
func (s *Protocol) SetType(val OptProtocolType) {
	s.Type = val
}

// SetSpecificationUrl sets the value of SpecificationUrl.
func (s *Protocol) SetSpecificationUrl(val OptURI) {
	s.SpecificationUrl = val
}

// The type of protocol.
type ProtocolType string

const (
	ProtocolTypeA2A       ProtocolType = "A2A"
	ProtocolTypeOpenAPI   ProtocolType = "OpenAPI"
	ProtocolTypeMCPServer ProtocolType = "MCP-Server"
)

// AllValues returns all ProtocolType values.
func (ProtocolType) AllValues() []ProtocolType {
	return []ProtocolType{
		ProtocolTypeA2A,
		ProtocolTypeOpenAPI,
		ProtocolTypeMCPServer,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ProtocolType) MarshalText() ([]byte, error) {
	switch s {
	case ProtocolTypeA2A:
		return []byte(s), nil
	case ProtocolTypeOpenAPI:
		return []byte(s), nil
	case ProtocolTypeMCPServer:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ProtocolType) UnmarshalText(data []byte) error {
	switch ProtocolType(data) {
	case ProtocolTypeA2A:
		*s = ProtocolTypeA2A
		return nil
	case ProtocolTypeOpenAPI:
		*s = ProtocolTypeOpenAPI
		return nil
	case ProtocolTypeMCPServer:
		*s = ProtocolTypeMCPServer
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// A reference to another SCIM resource.
// Ref: #/components/schemas/Reference
type Reference struct {
	// The identifier of the referenced resource.
	Value OptString `json:"value"`
	// The URI of the referenced resource.
	Ref OptURI `json:"$ref"`
	// A human-readable name for the referenced resource.
	Display OptString `json:"display"`
}

// GetValue returns the value of Value.
func (s *Reference) GetValue() OptString {
	return s.Value
}

// GetRef returns the value of Ref.
func (s *Reference) GetRef() OptURI {
	return s.Ref
}

// GetDisplay returns the value of Display.
func (s *Reference) GetDisplay() OptString {
	return s.Display
}

// SetValue sets the value of Value.
func (s *Reference) SetValue(val OptString) {
	s.Value = val
}

// SetRef sets the value of Ref.
func (s *Reference) SetRef(val OptURI) {
	s.Ref = val
}

// SetDisplay sets the value of Display.
func (s *Reference) SetDisplay(val OptString) {
	s.Display = val
}

type ReplaceAgentBadRequest Error

func (*ReplaceAgentBadRequest) replaceAgentRes() {}

type ReplaceAgentConflict Error

func (*ReplaceAgentConflict) replaceAgentRes() {}

type ReplaceAgentForbidden Error

func (*ReplaceAgentForbidden) replaceAgentRes() {}

type ReplaceAgentInternalServerError Error

func (*ReplaceAgentInternalServerError) replaceAgentRes() {}

type ReplaceAgentNotFound Error

func (*ReplaceAgentNotFound) replaceAgentRes() {}

type ReplaceAgentUnauthorized Error

func (*ReplaceAgentUnauthorized) replaceAgentRes() {}

type ReplaceAgenticApplicationBadRequest Error

func (*ReplaceAgenticApplicationBadRequest) replaceAgenticApplicationRes() {}

type ReplaceAgenticApplicationConflict Error

func (*ReplaceAgenticApplicationConflict) replaceAgenticApplicationRes() {}

type ReplaceAgenticApplicationForbidden Error

func (*ReplaceAgenticApplicationForbidden) replaceAgenticApplicationRes() {}

type ReplaceAgenticApplicationInternalServerError Error

func (*ReplaceAgenticApplicationInternalServerError) replaceAgenticApplicationRes() {}

type ReplaceAgenticApplicationNotFound Error

func (*ReplaceAgenticApplicationNotFound) replaceAgenticApplicationRes() {}

type ReplaceAgenticApplicationUnauthorized Error

func (*ReplaceAgenticApplicationUnauthorized) replaceAgenticApplicationRes() {}

// A role assigned to an agent.
// Ref: #/components/schemas/Role
type Role struct {
	// The value of the role.
	Value OptString `json:"value"`
	// A human-readable name for the role.
	Display OptString `json:"display"`
	// A label indicating the role's function.
	Type OptString `json:"type"`
	// Whether this is the primary role.
	Primary OptBool `json:"primary"`
}

// GetValue returns the value of Value.
func (s *Role) GetValue() OptString {
	return s.Value
}

// GetDisplay returns the value of Display.
func (s *Role) GetDisplay() OptString {
	return s.Display
}

// GetType returns the value of Type.
func (s *Role) GetType() OptString {
	return s.Type
}

// GetPrimary returns the value of Primary.
func (s *Role) GetPrimary() OptBool {
	return s.Primary
}

// SetValue sets the value of Value.
func (s *Role) SetValue(val OptString) {
	s.Value = val
}

// SetDisplay sets the value of Display.
func (s *Role) SetDisplay(val OptString) {
	s.Display = val
}

// SetType sets the value of Type.
func (s *Role) SetType(val OptString) {
	s.Type = val
}

// SetPrimary sets the value of Primary.
func (s *Role) SetPrimary(val OptBool) {
	s.Primary = val
}

// SCIM Service Provider Configuration with Agent Extension support.
// Ref: #/components/schemas/ServiceProviderConfig
type ServiceProviderConfig struct {
	Schemas []string `json:"schemas"`
	// URI for the service provider's documentation.
	DocumentationUri      OptURI                                           `json:"documentationUri"`
	Patch                 OptServiceProviderConfigPatch                    `json:"patch"`
	Bulk                  OptServiceProviderConfigBulk                     `json:"bulk"`
	Filter                OptServiceProviderConfigFilter                   `json:"filter"`
	ChangePassword        OptServiceProviderConfigChangePassword           `json:"changePassword"`
	Sort                  OptServiceProviderConfigSort                     `json:"sort"`
	Etag                  OptServiceProviderConfigEtag                     `json:"etag"`
	AuthenticationSchemes []ServiceProviderConfigAuthenticationSchemesItem `json:"authenticationSchemes"`
	AgentExtension        OptAgentExtensionConfig                          `json:"agentExtension"`
	Meta                  OptMeta                                          `json:"meta"`
}

// GetSchemas returns the value of Schemas.
func (s *ServiceProviderConfig) GetSchemas() []string {
	return s.Schemas
}

// GetDocumentationUri returns the value of DocumentationUri.
func (s *ServiceProviderConfig) GetDocumentationUri() OptURI {
	return s.DocumentationUri
}

// GetPatch returns the value of Patch.
func (s *ServiceProviderConfig) GetPatch() OptServiceProviderConfigPatch {
	return s.Patch
}

// GetBulk returns the value of Bulk.
func (s *ServiceProviderConfig) GetBulk() OptServiceProviderConfigBulk {
	return s.Bulk
}

// GetFilter returns the value of Filter.
func (s *ServiceProviderConfig) GetFilter() OptServiceProviderConfigFilter {
	return s.Filter
}

// GetChangePassword returns the value of ChangePassword.
func (s *ServiceProviderConfig) GetChangePassword() OptServiceProviderConfigChangePassword {
	return s.ChangePassword
}

// GetSort returns the value of Sort.
func (s *ServiceProviderConfig) GetSort() OptServiceProviderConfigSort {
	return s.Sort
}

// GetEtag returns the value of Etag.
func (s *ServiceProviderConfig) GetEtag() OptServiceProviderConfigEtag {
	return s.Etag
}

// GetAuthenticationSchemes returns the value of AuthenticationSchemes.
func (s *ServiceProviderConfig) GetAuthenticationSchemes() []ServiceProviderConfigAuthenticationSchemesItem {
	return s.AuthenticationSchemes
}

// GetAgentExtension returns the value of AgentExtension.
func (s *ServiceProviderConfig) GetAgentExtension() OptAgentExtensionConfig {
	return s.AgentExtension
}

// GetMeta returns the value of Meta.
func (s *ServiceProviderConfig) GetMeta() OptMeta {
	return s.Meta
}

// SetSchemas sets the value of Schemas.
func (s *ServiceProviderConfig) SetSchemas(val []string) {
	s.Schemas = val
}

// SetDocumentationUri sets the value of DocumentationUri.
func (s *ServiceProviderConfig) SetDocumentationUri(val OptURI) {
	s.DocumentationUri = val
}

// SetPatch sets the value of Patch.
func (s *ServiceProviderConfig) SetPatch(val OptServiceProviderConfigPatch) {
	s.Patch = val
}

// SetBulk sets the value of Bulk.
func (s *ServiceProviderConfig) SetBulk(val OptServiceProviderConfigBulk) {
	s.Bulk = val
}

// SetFilter sets the value of Filter.
func (s *ServiceProviderConfig) SetFilter(val OptServiceProviderConfigFilter) {
	s.Filter = val
}

// SetChangePassword sets the value of ChangePassword.
func (s *ServiceProviderConfig) SetChangePassword(val OptServiceProviderConfigChangePassword) {
	s.ChangePassword = val
}

// SetSort sets the value of Sort.
func (s *ServiceProviderConfig) SetSort(val OptServiceProviderConfigSort) {
	s.Sort = val
}

// SetEtag sets the value of Etag.
func (s *ServiceProviderConfig) SetEtag(val OptServiceProviderConfigEtag) {
	s.Etag = val
}

// SetAuthenticationSchemes sets the value of AuthenticationSchemes.
func (s *ServiceProviderConfig) SetAuthenticationSchemes(val []ServiceProviderConfigAuthenticationSchemesItem) {
	s.AuthenticationSchemes = val
}

// SetAgentExtension sets the value of AgentExtension.
func (s *ServiceProviderConfig) SetAgentExtension(val OptAgentExtensionConfig) {
	s.AgentExtension = val
}

// SetMeta sets the value of Meta.
func (s *ServiceProviderConfig) SetMeta(val OptMeta) {
	s.Meta = val
}

func (*ServiceProviderConfig) getServiceProviderConfigRes() {}

type ServiceProviderConfigAuthenticationSchemesItem struct {
	Type             OptString `json:"type"`
	Name             OptString `json:"name"`
	Description      OptString `json:"description"`
	SpecUri          OptURI    `json:"specUri"`
	DocumentationUri OptURI    `json:"documentationUri"`
}

// GetType returns the value of Type.
func (s *ServiceProviderConfigAuthenticationSchemesItem) GetType() OptString {
	return s.Type
}

// GetName returns the value of Name.
func (s *ServiceProviderConfigAuthenticationSchemesItem) GetName() OptString {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *ServiceProviderConfigAuthenticationSchemesItem) GetDescription() OptString {
	return s.Description
}

// GetSpecUri returns the value of SpecUri.
func (s *ServiceProviderConfigAuthenticationSchemesItem) GetSpecUri() OptURI {
	return s.SpecUri
}

// GetDocumentationUri returns the value of DocumentationUri.
func (s *ServiceProviderConfigAuthenticationSchemesItem) GetDocumentationUri() OptURI {
	return s.DocumentationUri
}

// SetType sets the value of Type.
func (s *ServiceProviderConfigAuthenticationSchemesItem) SetType(val OptString) {
	s.Type = val
}

// SetName sets the value of Name.
func (s *ServiceProviderConfigAuthenticationSchemesItem) SetName(val OptString) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *ServiceProviderConfigAuthenticationSchemesItem) SetDescription(val OptString) {
	s.Description = val
}

// SetSpecUri sets the value of SpecUri.
func (s *ServiceProviderConfigAuthenticationSchemesItem) SetSpecUri(val OptURI) {
	s.SpecUri = val
}

// SetDocumentationUri sets the value of DocumentationUri.
func (s *ServiceProviderConfigAuthenticationSchemesItem) SetDocumentationUri(val OptURI) {
	s.DocumentationUri = val
}

type ServiceProviderConfigBulk struct {
	Supported      OptBool `json:"supported"`
	MaxOperations  OptInt  `json:"maxOperations"`
	MaxPayloadSize OptInt  `json:"maxPayloadSize"`
}

// GetSupported returns the value of Supported.
func (s *ServiceProviderConfigBulk) GetSupported() OptBool {
	return s.Supported
}

// GetMaxOperations returns the value of MaxOperations.
func (s *ServiceProviderConfigBulk) GetMaxOperations() OptInt {
	return s.MaxOperations
}

// GetMaxPayloadSize returns the value of MaxPayloadSize.
func (s *ServiceProviderConfigBulk) GetMaxPayloadSize() OptInt {
	return s.MaxPayloadSize
}

// SetSupported sets the value of Supported.
func (s *ServiceProviderConfigBulk) SetSupported(val OptBool) {
	s.Supported = val
}

// SetMaxOperations sets the value of MaxOperations.
func (s *ServiceProviderConfigBulk) SetMaxOperations(val OptInt) {
	s.MaxOperations = val
}

// SetMaxPayloadSize sets the value of MaxPayloadSize.
func (s *ServiceProviderConfigBulk) SetMaxPayloadSize(val OptInt) {
	s.MaxPayloadSize = val
}

type ServiceProviderConfigChangePassword struct {
	Supported OptBool `json:"supported"`
}

// GetSupported returns the value of Supported.
func (s *ServiceProviderConfigChangePassword) GetSupported() OptBool {
	return s.Supported
}

// SetSupported sets the value of Supported.
func (s *ServiceProviderConfigChangePassword) SetSupported(val OptBool) {
	s.Supported = val
}

type ServiceProviderConfigEtag struct {
	Supported OptBool `json:"supported"`
}

// GetSupported returns the value of Supported.
func (s *ServiceProviderConfigEtag) GetSupported() OptBool {
	return s.Supported
}

// SetSupported sets the value of Supported.
func (s *ServiceProviderConfigEtag) SetSupported(val OptBool) {
	s.Supported = val
}

type ServiceProviderConfigFilter struct {
	Supported  OptBool `json:"supported"`
	MaxResults OptInt  `json:"maxResults"`
}

// GetSupported returns the value of Supported.
func (s *ServiceProviderConfigFilter) GetSupported() OptBool {
	return s.Supported
}

// GetMaxResults returns the value of MaxResults.
func (s *ServiceProviderConfigFilter) GetMaxResults() OptInt {
	return s.MaxResults
}

// SetSupported sets the value of Supported.
func (s *ServiceProviderConfigFilter) SetSupported(val OptBool) {
	s.Supported = val
}

// SetMaxResults sets the value of MaxResults.
func (s *ServiceProviderConfigFilter) SetMaxResults(val OptInt) {
	s.MaxResults = val
}

type ServiceProviderConfigPatch struct {
	Supported OptBool `json:"supported"`
}

// GetSupported returns the value of Supported.
func (s *ServiceProviderConfigPatch) GetSupported() OptBool {
	return s.Supported
}

// SetSupported sets the value of Supported.
func (s *ServiceProviderConfigPatch) SetSupported(val OptBool) {
	s.Supported = val
}

type ServiceProviderConfigSort struct {
	Supported OptBool `json:"supported"`
}

// GetSupported returns the value of Supported.
func (s *ServiceProviderConfigSort) GetSupported() OptBool {
	return s.Supported
}

// SetSupported sets the value of Supported.
func (s *ServiceProviderConfigSort) SetSupported(val OptBool) {
	s.Supported = val
}

type SortOrder string

const (
	SortOrderAscending  SortOrder = "ascending"
	SortOrderDescending SortOrder = "descending"
)

// AllValues returns all SortOrder values.
func (SortOrder) AllValues() []SortOrder {
	return []SortOrder{
		SortOrderAscending,
		SortOrderDescending,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SortOrder) MarshalText() ([]byte, error) {
	switch s {
	case SortOrderAscending:
		return []byte(s), nil
	case SortOrderDescending:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SortOrder) UnmarshalText(data []byte) error {
	switch SortOrder(data) {
	case SortOrderAscending:
		*s = SortOrderAscending
		return nil
	case SortOrderDescending:
		*s = SortOrderDescending
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// An X.509 certificate.
// Ref: #/components/schemas/X509Certificate
type X509Certificate struct {
	// The DER-encoded X.509 certificate, base64 encoded.
	Value []byte `json:"value"`
	// A human-readable name for the certificate.
	Display OptString `json:"display"`
	// A label indicating the certificate's function.
	Type OptString `json:"type"`
	// Whether this is the primary certificate.
	Primary OptBool `json:"primary"`
}

// GetValue returns the value of Value.
func (s *X509Certificate) GetValue() []byte {
	return s.Value
}

// GetDisplay returns the value of Display.
func (s *X509Certificate) GetDisplay() OptString {
	return s.Display
}

// GetType returns the value of Type.
func (s *X509Certificate) GetType() OptString {
	return s.Type
}

// GetPrimary returns the value of Primary.
func (s *X509Certificate) GetPrimary() OptBool {
	return s.Primary
}

// SetValue sets the value of Value.
func (s *X509Certificate) SetValue(val []byte) {
	s.Value = val
}

// SetDisplay sets the value of Display.
func (s *X509Certificate) SetDisplay(val OptString) {
	s.Display = val
}

// SetType sets the value of Type.
func (s *X509Certificate) SetType(val OptString) {
	s.Type = val
}

// SetPrimary sets the value of Primary.
func (s *X509Certificate) SetPrimary(val OptBool) {
	s.Primary = val
}
