// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateAgent implements createAgent operation.
	//
	// Create a new agent resource.
	//
	// POST /Agents
	CreateAgent(ctx context.Context, req *AgentCreate) (CreateAgentRes, error)
	// CreateAgenticApplication implements createAgenticApplication operation.
	//
	// Create a new agentic application resource.
	//
	// POST /AgenticApplications
	CreateAgenticApplication(ctx context.Context, req *AgenticApplicationCreate) (CreateAgenticApplicationRes, error)
	// DeleteAgent implements deleteAgent operation.
	//
	// Delete an existing agent resource.
	//
	// DELETE /Agents/{id}
	DeleteAgent(ctx context.Context, params DeleteAgentParams) (DeleteAgentRes, error)
	// DeleteAgenticApplication implements deleteAgenticApplication operation.
	//
	// Delete an existing agentic application resource.
	//
	// DELETE /AgenticApplications/{id}
	DeleteAgenticApplication(ctx context.Context, params DeleteAgenticApplicationParams) (DeleteAgenticApplicationRes, error)
	// GetAgent implements getAgent operation.
	//
	// Retrieve a single agent by its unique identifier.
	//
	// GET /Agents/{id}
	GetAgent(ctx context.Context, params GetAgentParams) (GetAgentRes, error)
	// GetAgenticApplication implements getAgenticApplication operation.
	//
	// Retrieve a single agentic application by its unique identifier.
	//
	// GET /AgenticApplications/{id}
	GetAgenticApplication(ctx context.Context, params GetAgenticApplicationParams) (GetAgenticApplicationRes, error)
	// GetServiceProviderConfig implements getServiceProviderConfig operation.
	//
	// Retrieve the service provider configuration including agent extension support.
	//
	// GET /ServiceProviderConfig
	GetServiceProviderConfig(ctx context.Context) (GetServiceProviderConfigRes, error)
	// ListAgenticApplications implements listAgenticApplications operation.
	//
	// Retrieve a list of agentic applications. Supports SCIM filtering on name, externalId, and
	// applicationUrls.value.
	//
	// GET /AgenticApplications
	ListAgenticApplications(ctx context.Context, params ListAgenticApplicationsParams) (ListAgenticApplicationsRes, error)
	// ListAgents implements listAgents operation.
	//
	// Retrieve a list of agents. Supports SCIM filtering on name and externalId.
	//
	// GET /Agents
	ListAgents(ctx context.Context, params ListAgentsParams) (ListAgentsRes, error)
	// PatchAgent implements patchAgent operation.
	//
	// Partially update an existing agent resource using SCIM PATCH operations.
	//
	// PATCH /Agents/{id}
	PatchAgent(ctx context.Context, req *PatchRequest, params PatchAgentParams) (PatchAgentRes, error)
	// PatchAgenticApplication implements patchAgenticApplication operation.
	//
	// Partially update an existing agentic application resource using SCIM PATCH operations.
	//
	// PATCH /AgenticApplications/{id}
	PatchAgenticApplication(ctx context.Context, req *PatchRequest, params PatchAgenticApplicationParams) (PatchAgenticApplicationRes, error)
	// ReplaceAgent implements replaceAgent operation.
	//
	// Replace an existing agent resource entirely.
	//
	// PUT /Agents/{id}
	ReplaceAgent(ctx context.Context, req *AgentCreate, params ReplaceAgentParams) (ReplaceAgentRes, error)
	// ReplaceAgenticApplication implements replaceAgenticApplication operation.
	//
	// Replace an existing agentic application resource entirely.
	//
	// PUT /AgenticApplications/{id}
	ReplaceAgenticApplication(ctx context.Context, req *AgenticApplicationCreate, params ReplaceAgenticApplicationParams) (ReplaceAgenticApplicationRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
